package entproto

import (
	"context"
	"entgo.io/ent/entc/gen"
	"fmt"
	"github.com/jhump/protoreflect/v2/protobuilder"
	"github.com/jhump/protoreflect/v2/protoprint"
	"os"
	"path"
)

type ProtoOption func(*ProtoGenerator)

func WithProtoOutput(output string) ProtoOption {
	return func(g *ProtoGenerator) {
		g.output = output
	}
}

func WithProtoPrinter(printer *protoprint.Printer) ProtoOption {
	return func(g *ProtoGenerator) {
		g.printer = printer
	}
}

func WithBuilder(builders ...ProtoBuilder) ProtoOption {
	return func(g *ProtoGenerator) {
		g.builders = append(g.builders, builders...)
	}
}

func NewProto(opts ...ProtoOption) *ProtoGenerator {
	g := &ProtoGenerator{output: "."}
	for _, opt := range opts {
		opt(g)
	}
	if g.printer == nil {
		g.printer = new(protoprint.Printer)
	}
	return g
}

type ProtoGenerator struct {
	builders []ProtoBuilder

	output string

	printer *protoprint.Printer
}

func (p *ProtoGenerator) Generate(ctx context.Context, graph *gen.Graph) error {
	c := &Context{Context: ctx}
	var results []*File
	for _, node := range graph.Nodes {
		for _, b := range p.builders {
			file, err := b.Build(c, node)
			if err != nil {
				return err
			}
			c = c.With(file.FileBuilder)
			results = append(results, file)
		}
	}
	for _, file := range results {
		if err := file.CallDelay(c); err != nil {
			return err
		}
	}
	for idx, file := range results {
		if err := p.write(idx, file.FileBuilder); err != nil {
			return err
		}
	}
	return nil
}

func (p *ProtoGenerator) write(idx int, fb *protobuilder.FileBuilder) (err error) {
	fb.SetSyntaxComments(protobuilder.Comments{LeadingComment: "Code generated by entc-gen. https://github.com/syralon/entc-gen-go"})
	if fb.Path() == "" {
		fb.SetPath(fmt.Sprintf("generated_%03d.proto", idx+1))
	}
	filename := fmt.Sprintf("%s/%s", p.output, fb.Path())
	_ = os.MkdirAll(path.Dir(filename), 0700)
	file, err := os.OpenFile(filename, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}
	defer func() { err = file.Close() }()
	data, err := fb.Build()
	if err != nil {
		return err
	}
	return p.printer.PrintProtoFile(data, file)
}
