package entproto

import (
	"fmt"
	"github.com/jhump/protoreflect/v2/protobuilder"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

type builder struct {
	pkg   string
	goPkg string
}

func (b *builder) NewFile(filename string) *protobuilder.FileBuilder {
	file := protobuilder.NewFile(filename)
	file.SetComments(protobuilder.Comments{LeadingComment: "Code generated by entc-gen."})
	file.Syntax = protoreflect.Proto3
	file.SetPackageName(protoreflect.FullName(b.pkg))
	file.SetOptions(&descriptorpb.FileOptions{GoPackage: proto.String(b.goPkg)})
	return file
}

func (b *builder) NewService(name string) *protobuilder.ServiceBuilder {
	return protobuilder.NewService(protoreflect.Name(name + "Service"))
}

func (b *builder) NewMethod(file *protobuilder.FileBuilder, service *protobuilder.ServiceBuilder, method, name string) (*protobuilder.MessageBuilder, *protobuilder.MessageBuilder) {
	request := protobuilder.NewMessage(protoreflect.Name(fmt.Sprintf("%sRequest", name)))
	response := protobuilder.NewMessage(protoreflect.Name(fmt.Sprintf("%sResponse", name)))
	service.AddMethod(protobuilder.NewMethod(
		protoreflect.Name(method),
		protobuilder.RpcTypeMessage(request, false),
		protobuilder.RpcTypeMessage(response, false),
	))
	file.AddMessage(request)
	file.AddMessage(response)
	return request, response
}
