package entservice

import (
	"context"
	"entgo.io/ent/entc/gen"
	"fmt"
	"github.com/dave/jennifer/jen"
	"path"
	"strings"
)

type controllerBuilder struct {
	pkg        string
	entPackage string
}

func (s *controllerBuilder) Build(_ context.Context, node *gen.Type) (*jen.File, error) {
	file := jen.NewFile(fmt.Sprintf("%sservice", strings.ToLower(node.Name)))
	file.PackageComment("Code generated by entc-gen; DO NOT EDIT")
	file.PackageComment("https://github.com/syralon/entc-gen-go")
	//file.ImportAlias(s.protoPackage, "pb")

	name := fmt.Sprintf("%sService", node.Name)

	file.Type().Id(name).Struct(
		jen.Op("*").Qual(path.Join(s.pkg, "internal/service"), name),
	).Line()

	file.Func().Id("New" + name).
		Params(jen.Id("client").Op("*").Qual(s.entPackage, "Client")).Op("*").Id(name).
		Block(
			jen.Return(jen.Op("&").Id(name).Block(
				jen.Id(name).Op(":").Qual(path.Join(s.pkg, "internal/service"), name),
			)),
		)
	return file, nil
}

func controllerProvider(pkg, entPackage, protoPackage string, graph *gen.Graph) (*jen.File, error) {
	file := jen.NewFile("controller")
	file.PackageComment("Code generated by entc-gen; DO NOT EDIT")
	file.PackageComment("https://github.com/syralon/entc-gen-go")
	file.ImportAlias(protoPackage, "pb")
	f1 := make([]jen.Code, 0)
	f2 := make([]jen.Code, 0)
	for _, node := range graph.Nodes {
		name := fmt.Sprintf("%sService", node.Name)
		imp := fmt.Sprintf("%s/internal/controller/%sservice", pkg, strings.ToLower(node.Name))
		f1 = append(
			f1,
			jen.Id(fmt.Sprintf("%sService", node.Name)).Op("*").Qual(imp, name),
		)
		f2 = append(
			f2,
			jen.Id(name).Op(":").Qual(imp, fmt.Sprintf("New%sService", node.Name)).Call(jen.Id("client")),
		)
	}
	file.Type().Id("Service").Struct(f1...).Line()
	file.Func().Id("NewService").Params(jen.Id("client").Op("*").Qual(entPackage, "Client")).Op("*").Id("Services").Block(
		jen.Return(jen.Op("*").Id("Services").Block(f2...)),
	).Line()

	file.Var().Id("Provider").Op("=").Qual(pkgWire, "NewSet").Add(calls(jen.Id("NewServices"))).Line()
	return file, nil
}
