package entproto

import (
	"context"
	"fmt"

	"github.com/golang/protobuf/protoc-gen-go/descriptor"
	"github.com/jhump/protoreflect/v2/protobuilder"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

type Context struct {
	context.Context

	files    map[string]*protobuilder.FileBuilder
	enums    map[protoreflect.Name]*protobuilder.EnumBuilder
	messages map[protoreflect.Name]*protobuilder.MessageBuilder
}

func NewContext(ctx context.Context) *Context {
	return &Context{
		Context:  ctx,
		files:    map[string]*protobuilder.FileBuilder{},
		enums:    map[protoreflect.Name]*protobuilder.EnumBuilder{},
		messages: map[protoreflect.Name]*protobuilder.MessageBuilder{},
	}
}

func (c *Context) NewFile(filename, protoPackage, goPackage string) *protobuilder.FileBuilder {
	if c.files[filename] == nil {
		file := protobuilder.NewFile(filename)
		file.SetComments(protobuilder.Comments{LeadingComment: "Code generated by entc-gen."})
		file.Syntax = protoreflect.Proto3
		file.SetPackageName(protoreflect.FullName(protoPackage))
		file.SetOptions(&descriptorpb.FileOptions{GoPackage: proto.String(goPackage)})
		c.files[filename] = file
	}
	return c.files[filename]
}

func (c *Context) NewEnum(name string) *protobuilder.EnumBuilder {
	if c.enums[protoreflect.Name(name)] == nil {
		c.enums[protoreflect.Name(name)] = protobuilder.NewEnum(protoreflect.Name(name))
	}
	return c.enums[protoreflect.Name(name)]
}

func (c *Context) NewMessage(name string) *protobuilder.MessageBuilder {
	if c.messages[protoreflect.Name(name)] == nil {
		c.messages[protoreflect.Name(name)] = protobuilder.NewMessage(protoreflect.Name(name))
	}
	return c.messages[protoreflect.Name(name)]
}

func (c *Context) NewService(serviceName string) *protobuilder.ServiceBuilder {
	return protobuilder.NewService(protoreflect.Name(serviceName))
}

func (c *Context) NewMethod(service *protobuilder.ServiceBuilder, method, name string, opts *descriptor.MethodOptions) (*protobuilder.MessageBuilder, *protobuilder.MessageBuilder) {
	request := c.NewMessage(fmt.Sprintf("%sRequest", name))
	response := c.NewMessage(fmt.Sprintf("%sResponse", name))
	methodBuilder := protobuilder.NewMethod(
		protoreflect.Name(method),
		protobuilder.RpcTypeMessage(request, false),
		protobuilder.RpcTypeMessage(response, false),
	)
	if opts != nil {
		methodBuilder.SetOptions(opts)
	}
	service.AddMethod(methodBuilder)
	return request, response
}

func (c *Context) GetMessage(name protoreflect.Name) (*protobuilder.MessageBuilder, error) {
	if c.messages[name] != nil {
		return c.messages[name], nil
	}
	for _, file := range c.files {
		if message := file.GetMessage(name); message != nil {
			return message, nil
		}
	}
	return nil, ErrorMessageNotFound(name)
}

func (c *Context) GetEnum(name protoreflect.Name) (*protobuilder.EnumBuilder, error) {
	if c.enums[name] != nil {
		return c.enums[name], nil
	}
	for _, file := range c.files {
		if enum := file.GetEnum(name); enum != nil {
			return enum, nil
		}
	}
	return nil, ErrorEnumNotFound(name)
}
