// Code generated by "stringer -type ErrorReason -trimprefix ErrorReason"; DO NOT EDIT.

package entproto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorReasonUnknown-0]
	_ = x[ErrorReasonNotFound-1]
}

const _ErrorReason_name = "UnknownNotFound"

var _ErrorReason_index = [...]uint8{0, 7, 15}

func (i ErrorReason) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ErrorReason_index)-1 {
		return "ErrorReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorReason_name[_ErrorReason_index[idx]:_ErrorReason_index[idx+1]]
}
