// Code generated by "stringer -type ProtoType -trimprefix Proto"; DO NOT EDIT.

package entproto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Protoenum-1]
	_ = x[Protomessage-2]
}

const _ProtoType_name = "enummessage"

var _ProtoType_index = [...]uint8{0, 4, 11}

func (i ProtoType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ProtoType_index)-1 {
		return "ProtoType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProtoType_name[_ProtoType_index[idx]:_ProtoType_index[idx+1]]
}
