// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.26.1
// source: syralon/entproto/field.proto

package entproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PRECISION int32

const (
	PRECISION_MILLISECOND PRECISION = 0
	PRECISION_SECOND      PRECISION = 1
	PRECISION_MINUTE      PRECISION = 2
	PRECISION_HOUR        PRECISION = 3
	PRECISION_DAY         PRECISION = 4
)

// Enum value maps for PRECISION.
var (
	PRECISION_name = map[int32]string{
		0: "MILLISECOND",
		1: "SECOND",
		2: "MINUTE",
		3: "HOUR",
		4: "DAY",
	}
	PRECISION_value = map[string]int32{
		"MILLISECOND": 0,
		"SECOND":      1,
		"MINUTE":      2,
		"HOUR":        3,
		"DAY":         4,
	}
)

func (x PRECISION) Enum() *PRECISION {
	p := new(PRECISION)
	*p = x
	return p
}

func (x PRECISION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PRECISION) Descriptor() protoreflect.EnumDescriptor {
	return file_syralon_entproto_field_proto_enumTypes[0].Descriptor()
}

func (PRECISION) Type() protoreflect.EnumType {
	return &file_syralon_entproto_field_proto_enumTypes[0]
}

func (x PRECISION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PRECISION.Descriptor instead.
func (PRECISION) EnumDescriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{0}
}

type Int32List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []int32 `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
}

func (x *Int32List) Reset() {
	*x = Int32List{}
	mi := &file_syralon_entproto_field_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32List) ProtoMessage() {}

func (x *Int32List) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32List.ProtoReflect.Descriptor instead.
func (*Int32List) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{0}
}

func (x *Int32List) GetList() []int32 {
	if x != nil {
		return x.List
	}
	return nil
}

type Int64List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []int64 `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
}

func (x *Int64List) Reset() {
	*x = Int64List{}
	mi := &file_syralon_entproto_field_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64List) ProtoMessage() {}

func (x *Int64List) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64List.ProtoReflect.Descriptor instead.
func (*Int64List) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{1}
}

func (x *Int64List) GetList() []int64 {
	if x != nil {
		return x.List
	}
	return nil
}

type Uint32List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []uint32 `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
}

func (x *Uint32List) Reset() {
	*x = Uint32List{}
	mi := &file_syralon_entproto_field_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint32List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint32List) ProtoMessage() {}

func (x *Uint32List) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint32List.ProtoReflect.Descriptor instead.
func (*Uint32List) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{2}
}

func (x *Uint32List) GetList() []uint32 {
	if x != nil {
		return x.List
	}
	return nil
}

type Uint64List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []uint64 `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
}

func (x *Uint64List) Reset() {
	*x = Uint64List{}
	mi := &file_syralon_entproto_field_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint64List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64List) ProtoMessage() {}

func (x *Uint64List) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64List.ProtoReflect.Descriptor instead.
func (*Uint64List) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{3}
}

func (x *Uint64List) GetList() []uint64 {
	if x != nil {
		return x.List
	}
	return nil
}

type FloatList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []float32 `protobuf:"fixed32,1,rep,packed,name=list,proto3" json:"list,omitempty"`
}

func (x *FloatList) Reset() {
	*x = FloatList{}
	mi := &file_syralon_entproto_field_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatList) ProtoMessage() {}

func (x *FloatList) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatList.ProtoReflect.Descriptor instead.
func (*FloatList) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{4}
}

func (x *FloatList) GetList() []float32 {
	if x != nil {
		return x.List
	}
	return nil
}

type DoubleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []float64 `protobuf:"fixed64,1,rep,packed,name=list,proto3" json:"list,omitempty"`
}

func (x *DoubleList) Reset() {
	*x = DoubleList{}
	mi := &file_syralon_entproto_field_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleList) ProtoMessage() {}

func (x *DoubleList) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleList.ProtoReflect.Descriptor instead.
func (*DoubleList) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{5}
}

func (x *DoubleList) GetList() []float64 {
	if x != nil {
		return x.List
	}
	return nil
}

type BoolList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []bool `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
}

func (x *BoolList) Reset() {
	*x = BoolList{}
	mi := &file_syralon_entproto_field_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolList) ProtoMessage() {}

func (x *BoolList) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolList.ProtoReflect.Descriptor instead.
func (*BoolList) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{6}
}

func (x *BoolList) GetList() []bool {
	if x != nil {
		return x.List
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_syralon_entproto_field_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{7}
}

func (x *StringList) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

type TimestampList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*timestamppb.Timestamp `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *TimestampList) Reset() {
	*x = TimestampList{}
	mi := &file_syralon_entproto_field_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampList) ProtoMessage() {}

func (x *TimestampList) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampList.ProtoReflect.Descriptor instead.
func (*TimestampList) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{8}
}

func (x *TimestampList) GetList() []*timestamppb.Timestamp {
	if x != nil {
		return x.List
	}
	return nil
}

type DurationList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*durationpb.Duration `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *DurationList) Reset() {
	*x = DurationList{}
	mi := &file_syralon_entproto_field_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationList) ProtoMessage() {}

func (x *DurationList) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationList.ProtoReflect.Descriptor instead.
func (*DurationList) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{9}
}

func (x *DurationList) GetList() []*durationpb.Duration {
	if x != nil {
		return x.List
	}
	return nil
}

type BytesList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List [][]byte `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *BytesList) Reset() {
	*x = BytesList{}
	mi := &file_syralon_entproto_field_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesList) ProtoMessage() {}

func (x *BytesList) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesList.ProtoReflect.Descriptor instead.
func (*BytesList) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{10}
}

func (x *BytesList) GetList() [][]byte {
	if x != nil {
		return x.List
	}
	return nil
}

type Int32Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operator:
	//
	//	*Int32Field_Eq
	//	*Int32Field_Ne
	//	*Int32Field_Gt
	//	*Int32Field_Gte
	//	*Int32Field_Lt
	//	*Int32Field_Lte
	//	*Int32Field_Between
	//	*Int32Field_In
	//	*Int32Field_NotIn
	Operator isInt32Field_Operator `protobuf_oneof:"operator"`
}

func (x *Int32Field) Reset() {
	*x = Int32Field{}
	mi := &file_syralon_entproto_field_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Field) ProtoMessage() {}

func (x *Int32Field) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Field.ProtoReflect.Descriptor instead.
func (*Int32Field) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{11}
}

func (m *Int32Field) GetOperator() isInt32Field_Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (x *Int32Field) GetEq() int32 {
	if x, ok := x.GetOperator().(*Int32Field_Eq); ok {
		return x.Eq
	}
	return 0
}

func (x *Int32Field) GetNe() int32 {
	if x, ok := x.GetOperator().(*Int32Field_Ne); ok {
		return x.Ne
	}
	return 0
}

func (x *Int32Field) GetGt() int32 {
	if x, ok := x.GetOperator().(*Int32Field_Gt); ok {
		return x.Gt
	}
	return 0
}

func (x *Int32Field) GetGte() int32 {
	if x, ok := x.GetOperator().(*Int32Field_Gte); ok {
		return x.Gte
	}
	return 0
}

func (x *Int32Field) GetLt() int32 {
	if x, ok := x.GetOperator().(*Int32Field_Lt); ok {
		return x.Lt
	}
	return 0
}

func (x *Int32Field) GetLte() int32 {
	if x, ok := x.GetOperator().(*Int32Field_Lte); ok {
		return x.Lte
	}
	return 0
}

func (x *Int32Field) GetBetween() *Int32List {
	if x, ok := x.GetOperator().(*Int32Field_Between); ok {
		return x.Between
	}
	return nil
}

func (x *Int32Field) GetIn() *Int32List {
	if x, ok := x.GetOperator().(*Int32Field_In); ok {
		return x.In
	}
	return nil
}

func (x *Int32Field) GetNotIn() *Int32List {
	if x, ok := x.GetOperator().(*Int32Field_NotIn); ok {
		return x.NotIn
	}
	return nil
}

type isInt32Field_Operator interface {
	isInt32Field_Operator()
}

type Int32Field_Eq struct {
	Eq int32 `protobuf:"varint,1,opt,name=eq,proto3,oneof"`
}

type Int32Field_Ne struct {
	Ne int32 `protobuf:"varint,2,opt,name=ne,proto3,oneof"`
}

type Int32Field_Gt struct {
	Gt int32 `protobuf:"varint,3,opt,name=gt,proto3,oneof"`
}

type Int32Field_Gte struct {
	Gte int32 `protobuf:"varint,4,opt,name=gte,proto3,oneof"`
}

type Int32Field_Lt struct {
	Lt int32 `protobuf:"varint,5,opt,name=lt,proto3,oneof"`
}

type Int32Field_Lte struct {
	Lte int32 `protobuf:"varint,6,opt,name=lte,proto3,oneof"`
}

type Int32Field_Between struct {
	Between *Int32List `protobuf:"bytes,7,opt,name=between,proto3,oneof"`
}

type Int32Field_In struct {
	In *Int32List `protobuf:"bytes,8,opt,name=in,proto3,oneof"`
}

type Int32Field_NotIn struct {
	NotIn *Int32List `protobuf:"bytes,9,opt,name=not_in,json=notIn,proto3,oneof"`
}

func (*Int32Field_Eq) isInt32Field_Operator() {}

func (*Int32Field_Ne) isInt32Field_Operator() {}

func (*Int32Field_Gt) isInt32Field_Operator() {}

func (*Int32Field_Gte) isInt32Field_Operator() {}

func (*Int32Field_Lt) isInt32Field_Operator() {}

func (*Int32Field_Lte) isInt32Field_Operator() {}

func (*Int32Field_Between) isInt32Field_Operator() {}

func (*Int32Field_In) isInt32Field_Operator() {}

func (*Int32Field_NotIn) isInt32Field_Operator() {}

type Int64Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operator:
	//
	//	*Int64Field_Eq
	//	*Int64Field_Ne
	//	*Int64Field_Gt
	//	*Int64Field_Gte
	//	*Int64Field_Lt
	//	*Int64Field_Lte
	//	*Int64Field_Between
	//	*Int64Field_In
	//	*Int64Field_NotIn
	Operator isInt64Field_Operator `protobuf_oneof:"operator"`
}

func (x *Int64Field) Reset() {
	*x = Int64Field{}
	mi := &file_syralon_entproto_field_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Field) ProtoMessage() {}

func (x *Int64Field) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Field.ProtoReflect.Descriptor instead.
func (*Int64Field) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{12}
}

func (m *Int64Field) GetOperator() isInt64Field_Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (x *Int64Field) GetEq() int64 {
	if x, ok := x.GetOperator().(*Int64Field_Eq); ok {
		return x.Eq
	}
	return 0
}

func (x *Int64Field) GetNe() int64 {
	if x, ok := x.GetOperator().(*Int64Field_Ne); ok {
		return x.Ne
	}
	return 0
}

func (x *Int64Field) GetGt() int64 {
	if x, ok := x.GetOperator().(*Int64Field_Gt); ok {
		return x.Gt
	}
	return 0
}

func (x *Int64Field) GetGte() int64 {
	if x, ok := x.GetOperator().(*Int64Field_Gte); ok {
		return x.Gte
	}
	return 0
}

func (x *Int64Field) GetLt() int64 {
	if x, ok := x.GetOperator().(*Int64Field_Lt); ok {
		return x.Lt
	}
	return 0
}

func (x *Int64Field) GetLte() int64 {
	if x, ok := x.GetOperator().(*Int64Field_Lte); ok {
		return x.Lte
	}
	return 0
}

func (x *Int64Field) GetBetween() *Int64List {
	if x, ok := x.GetOperator().(*Int64Field_Between); ok {
		return x.Between
	}
	return nil
}

func (x *Int64Field) GetIn() *Int64List {
	if x, ok := x.GetOperator().(*Int64Field_In); ok {
		return x.In
	}
	return nil
}

func (x *Int64Field) GetNotIn() *Int64List {
	if x, ok := x.GetOperator().(*Int64Field_NotIn); ok {
		return x.NotIn
	}
	return nil
}

type isInt64Field_Operator interface {
	isInt64Field_Operator()
}

type Int64Field_Eq struct {
	Eq int64 `protobuf:"varint,1,opt,name=eq,proto3,oneof"`
}

type Int64Field_Ne struct {
	Ne int64 `protobuf:"varint,2,opt,name=ne,proto3,oneof"`
}

type Int64Field_Gt struct {
	Gt int64 `protobuf:"varint,3,opt,name=gt,proto3,oneof"`
}

type Int64Field_Gte struct {
	Gte int64 `protobuf:"varint,4,opt,name=gte,proto3,oneof"`
}

type Int64Field_Lt struct {
	Lt int64 `protobuf:"varint,5,opt,name=lt,proto3,oneof"`
}

type Int64Field_Lte struct {
	Lte int64 `protobuf:"varint,6,opt,name=lte,proto3,oneof"`
}

type Int64Field_Between struct {
	Between *Int64List `protobuf:"bytes,7,opt,name=between,proto3,oneof"`
}

type Int64Field_In struct {
	In *Int64List `protobuf:"bytes,8,opt,name=in,proto3,oneof"`
}

type Int64Field_NotIn struct {
	NotIn *Int64List `protobuf:"bytes,9,opt,name=not_in,json=notIn,proto3,oneof"`
}

func (*Int64Field_Eq) isInt64Field_Operator() {}

func (*Int64Field_Ne) isInt64Field_Operator() {}

func (*Int64Field_Gt) isInt64Field_Operator() {}

func (*Int64Field_Gte) isInt64Field_Operator() {}

func (*Int64Field_Lt) isInt64Field_Operator() {}

func (*Int64Field_Lte) isInt64Field_Operator() {}

func (*Int64Field_Between) isInt64Field_Operator() {}

func (*Int64Field_In) isInt64Field_Operator() {}

func (*Int64Field_NotIn) isInt64Field_Operator() {}

type Uint32Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operator:
	//
	//	*Uint32Field_Eq
	//	*Uint32Field_Ne
	//	*Uint32Field_Gt
	//	*Uint32Field_Gte
	//	*Uint32Field_Lt
	//	*Uint32Field_Lte
	//	*Uint32Field_Between
	//	*Uint32Field_In
	//	*Uint32Field_NotIn
	Operator isUint32Field_Operator `protobuf_oneof:"operator"`
}

func (x *Uint32Field) Reset() {
	*x = Uint32Field{}
	mi := &file_syralon_entproto_field_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint32Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint32Field) ProtoMessage() {}

func (x *Uint32Field) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint32Field.ProtoReflect.Descriptor instead.
func (*Uint32Field) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{13}
}

func (m *Uint32Field) GetOperator() isUint32Field_Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (x *Uint32Field) GetEq() uint32 {
	if x, ok := x.GetOperator().(*Uint32Field_Eq); ok {
		return x.Eq
	}
	return 0
}

func (x *Uint32Field) GetNe() uint32 {
	if x, ok := x.GetOperator().(*Uint32Field_Ne); ok {
		return x.Ne
	}
	return 0
}

func (x *Uint32Field) GetGt() uint32 {
	if x, ok := x.GetOperator().(*Uint32Field_Gt); ok {
		return x.Gt
	}
	return 0
}

func (x *Uint32Field) GetGte() uint32 {
	if x, ok := x.GetOperator().(*Uint32Field_Gte); ok {
		return x.Gte
	}
	return 0
}

func (x *Uint32Field) GetLt() uint32 {
	if x, ok := x.GetOperator().(*Uint32Field_Lt); ok {
		return x.Lt
	}
	return 0
}

func (x *Uint32Field) GetLte() uint32 {
	if x, ok := x.GetOperator().(*Uint32Field_Lte); ok {
		return x.Lte
	}
	return 0
}

func (x *Uint32Field) GetBetween() *Uint32List {
	if x, ok := x.GetOperator().(*Uint32Field_Between); ok {
		return x.Between
	}
	return nil
}

func (x *Uint32Field) GetIn() *Uint32List {
	if x, ok := x.GetOperator().(*Uint32Field_In); ok {
		return x.In
	}
	return nil
}

func (x *Uint32Field) GetNotIn() *Uint32List {
	if x, ok := x.GetOperator().(*Uint32Field_NotIn); ok {
		return x.NotIn
	}
	return nil
}

type isUint32Field_Operator interface {
	isUint32Field_Operator()
}

type Uint32Field_Eq struct {
	Eq uint32 `protobuf:"varint,1,opt,name=eq,proto3,oneof"`
}

type Uint32Field_Ne struct {
	Ne uint32 `protobuf:"varint,2,opt,name=ne,proto3,oneof"`
}

type Uint32Field_Gt struct {
	Gt uint32 `protobuf:"varint,3,opt,name=gt,proto3,oneof"`
}

type Uint32Field_Gte struct {
	Gte uint32 `protobuf:"varint,4,opt,name=gte,proto3,oneof"`
}

type Uint32Field_Lt struct {
	Lt uint32 `protobuf:"varint,5,opt,name=lt,proto3,oneof"`
}

type Uint32Field_Lte struct {
	Lte uint32 `protobuf:"varint,6,opt,name=lte,proto3,oneof"`
}

type Uint32Field_Between struct {
	Between *Uint32List `protobuf:"bytes,7,opt,name=between,proto3,oneof"`
}

type Uint32Field_In struct {
	In *Uint32List `protobuf:"bytes,8,opt,name=in,proto3,oneof"`
}

type Uint32Field_NotIn struct {
	NotIn *Uint32List `protobuf:"bytes,9,opt,name=not_in,json=notIn,proto3,oneof"`
}

func (*Uint32Field_Eq) isUint32Field_Operator() {}

func (*Uint32Field_Ne) isUint32Field_Operator() {}

func (*Uint32Field_Gt) isUint32Field_Operator() {}

func (*Uint32Field_Gte) isUint32Field_Operator() {}

func (*Uint32Field_Lt) isUint32Field_Operator() {}

func (*Uint32Field_Lte) isUint32Field_Operator() {}

func (*Uint32Field_Between) isUint32Field_Operator() {}

func (*Uint32Field_In) isUint32Field_Operator() {}

func (*Uint32Field_NotIn) isUint32Field_Operator() {}

type Uint64Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operator:
	//
	//	*Uint64Field_Eq
	//	*Uint64Field_Ne
	//	*Uint64Field_Gt
	//	*Uint64Field_Gte
	//	*Uint64Field_Lt
	//	*Uint64Field_Lte
	//	*Uint64Field_Between
	//	*Uint64Field_In
	//	*Uint64Field_NotIn
	Operator isUint64Field_Operator `protobuf_oneof:"operator"`
}

func (x *Uint64Field) Reset() {
	*x = Uint64Field{}
	mi := &file_syralon_entproto_field_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint64Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64Field) ProtoMessage() {}

func (x *Uint64Field) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64Field.ProtoReflect.Descriptor instead.
func (*Uint64Field) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{14}
}

func (m *Uint64Field) GetOperator() isUint64Field_Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (x *Uint64Field) GetEq() uint64 {
	if x, ok := x.GetOperator().(*Uint64Field_Eq); ok {
		return x.Eq
	}
	return 0
}

func (x *Uint64Field) GetNe() uint64 {
	if x, ok := x.GetOperator().(*Uint64Field_Ne); ok {
		return x.Ne
	}
	return 0
}

func (x *Uint64Field) GetGt() uint64 {
	if x, ok := x.GetOperator().(*Uint64Field_Gt); ok {
		return x.Gt
	}
	return 0
}

func (x *Uint64Field) GetGte() uint64 {
	if x, ok := x.GetOperator().(*Uint64Field_Gte); ok {
		return x.Gte
	}
	return 0
}

func (x *Uint64Field) GetLt() uint64 {
	if x, ok := x.GetOperator().(*Uint64Field_Lt); ok {
		return x.Lt
	}
	return 0
}

func (x *Uint64Field) GetLte() uint64 {
	if x, ok := x.GetOperator().(*Uint64Field_Lte); ok {
		return x.Lte
	}
	return 0
}

func (x *Uint64Field) GetBetween() *Uint64List {
	if x, ok := x.GetOperator().(*Uint64Field_Between); ok {
		return x.Between
	}
	return nil
}

func (x *Uint64Field) GetIn() *Uint64List {
	if x, ok := x.GetOperator().(*Uint64Field_In); ok {
		return x.In
	}
	return nil
}

func (x *Uint64Field) GetNotIn() *Uint64List {
	if x, ok := x.GetOperator().(*Uint64Field_NotIn); ok {
		return x.NotIn
	}
	return nil
}

type isUint64Field_Operator interface {
	isUint64Field_Operator()
}

type Uint64Field_Eq struct {
	Eq uint64 `protobuf:"varint,1,opt,name=eq,proto3,oneof"`
}

type Uint64Field_Ne struct {
	Ne uint64 `protobuf:"varint,2,opt,name=ne,proto3,oneof"`
}

type Uint64Field_Gt struct {
	Gt uint64 `protobuf:"varint,3,opt,name=gt,proto3,oneof"`
}

type Uint64Field_Gte struct {
	Gte uint64 `protobuf:"varint,4,opt,name=gte,proto3,oneof"`
}

type Uint64Field_Lt struct {
	Lt uint64 `protobuf:"varint,5,opt,name=lt,proto3,oneof"`
}

type Uint64Field_Lte struct {
	Lte uint64 `protobuf:"varint,6,opt,name=lte,proto3,oneof"`
}

type Uint64Field_Between struct {
	Between *Uint64List `protobuf:"bytes,7,opt,name=between,proto3,oneof"`
}

type Uint64Field_In struct {
	In *Uint64List `protobuf:"bytes,8,opt,name=in,proto3,oneof"`
}

type Uint64Field_NotIn struct {
	NotIn *Uint64List `protobuf:"bytes,9,opt,name=not_in,json=notIn,proto3,oneof"`
}

func (*Uint64Field_Eq) isUint64Field_Operator() {}

func (*Uint64Field_Ne) isUint64Field_Operator() {}

func (*Uint64Field_Gt) isUint64Field_Operator() {}

func (*Uint64Field_Gte) isUint64Field_Operator() {}

func (*Uint64Field_Lt) isUint64Field_Operator() {}

func (*Uint64Field_Lte) isUint64Field_Operator() {}

func (*Uint64Field_Between) isUint64Field_Operator() {}

func (*Uint64Field_In) isUint64Field_Operator() {}

func (*Uint64Field_NotIn) isUint64Field_Operator() {}

type FloatField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operator:
	//
	//	*FloatField_Eq
	//	*FloatField_Ne
	//	*FloatField_Gt
	//	*FloatField_Gte
	//	*FloatField_Lt
	//	*FloatField_Lte
	//	*FloatField_Between
	//	*FloatField_In
	//	*FloatField_NotIn
	Operator isFloatField_Operator `protobuf_oneof:"operator"`
}

func (x *FloatField) Reset() {
	*x = FloatField{}
	mi := &file_syralon_entproto_field_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatField) ProtoMessage() {}

func (x *FloatField) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatField.ProtoReflect.Descriptor instead.
func (*FloatField) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{15}
}

func (m *FloatField) GetOperator() isFloatField_Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (x *FloatField) GetEq() float32 {
	if x, ok := x.GetOperator().(*FloatField_Eq); ok {
		return x.Eq
	}
	return 0
}

func (x *FloatField) GetNe() float32 {
	if x, ok := x.GetOperator().(*FloatField_Ne); ok {
		return x.Ne
	}
	return 0
}

func (x *FloatField) GetGt() float32 {
	if x, ok := x.GetOperator().(*FloatField_Gt); ok {
		return x.Gt
	}
	return 0
}

func (x *FloatField) GetGte() float32 {
	if x, ok := x.GetOperator().(*FloatField_Gte); ok {
		return x.Gte
	}
	return 0
}

func (x *FloatField) GetLt() float32 {
	if x, ok := x.GetOperator().(*FloatField_Lt); ok {
		return x.Lt
	}
	return 0
}

func (x *FloatField) GetLte() float32 {
	if x, ok := x.GetOperator().(*FloatField_Lte); ok {
		return x.Lte
	}
	return 0
}

func (x *FloatField) GetBetween() *FloatList {
	if x, ok := x.GetOperator().(*FloatField_Between); ok {
		return x.Between
	}
	return nil
}

func (x *FloatField) GetIn() *FloatList {
	if x, ok := x.GetOperator().(*FloatField_In); ok {
		return x.In
	}
	return nil
}

func (x *FloatField) GetNotIn() *FloatList {
	if x, ok := x.GetOperator().(*FloatField_NotIn); ok {
		return x.NotIn
	}
	return nil
}

type isFloatField_Operator interface {
	isFloatField_Operator()
}

type FloatField_Eq struct {
	Eq float32 `protobuf:"fixed32,1,opt,name=eq,proto3,oneof"`
}

type FloatField_Ne struct {
	Ne float32 `protobuf:"fixed32,2,opt,name=ne,proto3,oneof"`
}

type FloatField_Gt struct {
	Gt float32 `protobuf:"fixed32,3,opt,name=gt,proto3,oneof"`
}

type FloatField_Gte struct {
	Gte float32 `protobuf:"fixed32,4,opt,name=gte,proto3,oneof"`
}

type FloatField_Lt struct {
	Lt float32 `protobuf:"fixed32,5,opt,name=lt,proto3,oneof"`
}

type FloatField_Lte struct {
	Lte float32 `protobuf:"fixed32,6,opt,name=lte,proto3,oneof"`
}

type FloatField_Between struct {
	Between *FloatList `protobuf:"bytes,7,opt,name=between,proto3,oneof"`
}

type FloatField_In struct {
	In *FloatList `protobuf:"bytes,8,opt,name=in,proto3,oneof"`
}

type FloatField_NotIn struct {
	NotIn *FloatList `protobuf:"bytes,9,opt,name=not_in,json=notIn,proto3,oneof"`
}

func (*FloatField_Eq) isFloatField_Operator() {}

func (*FloatField_Ne) isFloatField_Operator() {}

func (*FloatField_Gt) isFloatField_Operator() {}

func (*FloatField_Gte) isFloatField_Operator() {}

func (*FloatField_Lt) isFloatField_Operator() {}

func (*FloatField_Lte) isFloatField_Operator() {}

func (*FloatField_Between) isFloatField_Operator() {}

func (*FloatField_In) isFloatField_Operator() {}

func (*FloatField_NotIn) isFloatField_Operator() {}

type DoubleField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operator:
	//
	//	*DoubleField_Eq
	//	*DoubleField_Ne
	//	*DoubleField_Gt
	//	*DoubleField_Gte
	//	*DoubleField_Lt
	//	*DoubleField_Lte
	//	*DoubleField_Between
	//	*DoubleField_In
	//	*DoubleField_NotIn
	Operator isDoubleField_Operator `protobuf_oneof:"operator"`
}

func (x *DoubleField) Reset() {
	*x = DoubleField{}
	mi := &file_syralon_entproto_field_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleField) ProtoMessage() {}

func (x *DoubleField) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleField.ProtoReflect.Descriptor instead.
func (*DoubleField) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{16}
}

func (m *DoubleField) GetOperator() isDoubleField_Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (x *DoubleField) GetEq() float64 {
	if x, ok := x.GetOperator().(*DoubleField_Eq); ok {
		return x.Eq
	}
	return 0
}

func (x *DoubleField) GetNe() float64 {
	if x, ok := x.GetOperator().(*DoubleField_Ne); ok {
		return x.Ne
	}
	return 0
}

func (x *DoubleField) GetGt() float64 {
	if x, ok := x.GetOperator().(*DoubleField_Gt); ok {
		return x.Gt
	}
	return 0
}

func (x *DoubleField) GetGte() float64 {
	if x, ok := x.GetOperator().(*DoubleField_Gte); ok {
		return x.Gte
	}
	return 0
}

func (x *DoubleField) GetLt() float64 {
	if x, ok := x.GetOperator().(*DoubleField_Lt); ok {
		return x.Lt
	}
	return 0
}

func (x *DoubleField) GetLte() float64 {
	if x, ok := x.GetOperator().(*DoubleField_Lte); ok {
		return x.Lte
	}
	return 0
}

func (x *DoubleField) GetBetween() *DoubleList {
	if x, ok := x.GetOperator().(*DoubleField_Between); ok {
		return x.Between
	}
	return nil
}

func (x *DoubleField) GetIn() *DoubleList {
	if x, ok := x.GetOperator().(*DoubleField_In); ok {
		return x.In
	}
	return nil
}

func (x *DoubleField) GetNotIn() *DoubleList {
	if x, ok := x.GetOperator().(*DoubleField_NotIn); ok {
		return x.NotIn
	}
	return nil
}

type isDoubleField_Operator interface {
	isDoubleField_Operator()
}

type DoubleField_Eq struct {
	Eq float64 `protobuf:"fixed64,1,opt,name=eq,proto3,oneof"`
}

type DoubleField_Ne struct {
	Ne float64 `protobuf:"fixed64,2,opt,name=ne,proto3,oneof"`
}

type DoubleField_Gt struct {
	Gt float64 `protobuf:"fixed64,3,opt,name=gt,proto3,oneof"`
}

type DoubleField_Gte struct {
	Gte float64 `protobuf:"fixed64,4,opt,name=gte,proto3,oneof"`
}

type DoubleField_Lt struct {
	Lt float64 `protobuf:"fixed64,5,opt,name=lt,proto3,oneof"`
}

type DoubleField_Lte struct {
	Lte float64 `protobuf:"fixed64,6,opt,name=lte,proto3,oneof"`
}

type DoubleField_Between struct {
	Between *DoubleList `protobuf:"bytes,7,opt,name=between,proto3,oneof"`
}

type DoubleField_In struct {
	In *DoubleList `protobuf:"bytes,8,opt,name=in,proto3,oneof"`
}

type DoubleField_NotIn struct {
	NotIn *DoubleList `protobuf:"bytes,9,opt,name=not_in,json=notIn,proto3,oneof"`
}

func (*DoubleField_Eq) isDoubleField_Operator() {}

func (*DoubleField_Ne) isDoubleField_Operator() {}

func (*DoubleField_Gt) isDoubleField_Operator() {}

func (*DoubleField_Gte) isDoubleField_Operator() {}

func (*DoubleField_Lt) isDoubleField_Operator() {}

func (*DoubleField_Lte) isDoubleField_Operator() {}

func (*DoubleField_Between) isDoubleField_Operator() {}

func (*DoubleField_In) isDoubleField_Operator() {}

func (*DoubleField_NotIn) isDoubleField_Operator() {}

type BoolField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operator:
	//
	//	*BoolField_Eq
	//	*BoolField_Ne
	Operator isBoolField_Operator `protobuf_oneof:"operator"`
}

func (x *BoolField) Reset() {
	*x = BoolField{}
	mi := &file_syralon_entproto_field_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolField) ProtoMessage() {}

func (x *BoolField) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolField.ProtoReflect.Descriptor instead.
func (*BoolField) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{17}
}

func (m *BoolField) GetOperator() isBoolField_Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (x *BoolField) GetEq() bool {
	if x, ok := x.GetOperator().(*BoolField_Eq); ok {
		return x.Eq
	}
	return false
}

func (x *BoolField) GetNe() bool {
	if x, ok := x.GetOperator().(*BoolField_Ne); ok {
		return x.Ne
	}
	return false
}

type isBoolField_Operator interface {
	isBoolField_Operator()
}

type BoolField_Eq struct {
	Eq bool `protobuf:"varint,1,opt,name=eq,proto3,oneof"`
}

type BoolField_Ne struct {
	Ne bool `protobuf:"varint,2,opt,name=ne,proto3,oneof"`
}

func (*BoolField_Eq) isBoolField_Operator() {}

func (*BoolField_Ne) isBoolField_Operator() {}

type StringField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operator:
	//
	//	*StringField_Eq
	//	*StringField_Ne
	//	*StringField_Gt
	//	*StringField_Gte
	//	*StringField_Lt
	//	*StringField_Lte
	//	*StringField_Between
	//	*StringField_In
	//	*StringField_NotIn
	//	*StringField_EqFold
	//	*StringField_Contains
	//	*StringField_HasPrefix
	//	*StringField_HasSuffix
	//	*StringField_Like
	Operator isStringField_Operator `protobuf_oneof:"operator"`
}

func (x *StringField) Reset() {
	*x = StringField{}
	mi := &file_syralon_entproto_field_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringField) ProtoMessage() {}

func (x *StringField) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringField.ProtoReflect.Descriptor instead.
func (*StringField) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{18}
}

func (m *StringField) GetOperator() isStringField_Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (x *StringField) GetEq() string {
	if x, ok := x.GetOperator().(*StringField_Eq); ok {
		return x.Eq
	}
	return ""
}

func (x *StringField) GetNe() string {
	if x, ok := x.GetOperator().(*StringField_Ne); ok {
		return x.Ne
	}
	return ""
}

func (x *StringField) GetGt() string {
	if x, ok := x.GetOperator().(*StringField_Gt); ok {
		return x.Gt
	}
	return ""
}

func (x *StringField) GetGte() string {
	if x, ok := x.GetOperator().(*StringField_Gte); ok {
		return x.Gte
	}
	return ""
}

func (x *StringField) GetLt() string {
	if x, ok := x.GetOperator().(*StringField_Lt); ok {
		return x.Lt
	}
	return ""
}

func (x *StringField) GetLte() string {
	if x, ok := x.GetOperator().(*StringField_Lte); ok {
		return x.Lte
	}
	return ""
}

func (x *StringField) GetBetween() *StringList {
	if x, ok := x.GetOperator().(*StringField_Between); ok {
		return x.Between
	}
	return nil
}

func (x *StringField) GetIn() *StringList {
	if x, ok := x.GetOperator().(*StringField_In); ok {
		return x.In
	}
	return nil
}

func (x *StringField) GetNotIn() *StringList {
	if x, ok := x.GetOperator().(*StringField_NotIn); ok {
		return x.NotIn
	}
	return nil
}

func (x *StringField) GetEqFold() string {
	if x, ok := x.GetOperator().(*StringField_EqFold); ok {
		return x.EqFold
	}
	return ""
}

func (x *StringField) GetContains() string {
	if x, ok := x.GetOperator().(*StringField_Contains); ok {
		return x.Contains
	}
	return ""
}

func (x *StringField) GetHasPrefix() string {
	if x, ok := x.GetOperator().(*StringField_HasPrefix); ok {
		return x.HasPrefix
	}
	return ""
}

func (x *StringField) GetHasSuffix() string {
	if x, ok := x.GetOperator().(*StringField_HasSuffix); ok {
		return x.HasSuffix
	}
	return ""
}

func (x *StringField) GetLike() string {
	if x, ok := x.GetOperator().(*StringField_Like); ok {
		return x.Like
	}
	return ""
}

type isStringField_Operator interface {
	isStringField_Operator()
}

type StringField_Eq struct {
	Eq string `protobuf:"bytes,1,opt,name=eq,proto3,oneof"`
}

type StringField_Ne struct {
	Ne string `protobuf:"bytes,2,opt,name=ne,proto3,oneof"`
}

type StringField_Gt struct {
	Gt string `protobuf:"bytes,3,opt,name=gt,proto3,oneof"`
}

type StringField_Gte struct {
	Gte string `protobuf:"bytes,4,opt,name=gte,proto3,oneof"`
}

type StringField_Lt struct {
	Lt string `protobuf:"bytes,5,opt,name=lt,proto3,oneof"`
}

type StringField_Lte struct {
	Lte string `protobuf:"bytes,6,opt,name=lte,proto3,oneof"`
}

type StringField_Between struct {
	Between *StringList `protobuf:"bytes,7,opt,name=between,proto3,oneof"`
}

type StringField_In struct {
	In *StringList `protobuf:"bytes,8,opt,name=in,proto3,oneof"`
}

type StringField_NotIn struct {
	NotIn *StringList `protobuf:"bytes,9,opt,name=not_in,json=notIn,proto3,oneof"`
}

type StringField_EqFold struct {
	EqFold string `protobuf:"bytes,10,opt,name=eq_fold,json=eqFold,proto3,oneof"`
}

type StringField_Contains struct {
	Contains string `protobuf:"bytes,11,opt,name=contains,proto3,oneof"`
}

type StringField_HasPrefix struct {
	HasPrefix string `protobuf:"bytes,12,opt,name=has_prefix,json=hasPrefix,proto3,oneof"`
}

type StringField_HasSuffix struct {
	HasSuffix string `protobuf:"bytes,13,opt,name=has_suffix,json=hasSuffix,proto3,oneof"`
}

type StringField_Like struct {
	Like string `protobuf:"bytes,14,opt,name=like,proto3,oneof"`
}

func (*StringField_Eq) isStringField_Operator() {}

func (*StringField_Ne) isStringField_Operator() {}

func (*StringField_Gt) isStringField_Operator() {}

func (*StringField_Gte) isStringField_Operator() {}

func (*StringField_Lt) isStringField_Operator() {}

func (*StringField_Lte) isStringField_Operator() {}

func (*StringField_Between) isStringField_Operator() {}

func (*StringField_In) isStringField_Operator() {}

func (*StringField_NotIn) isStringField_Operator() {}

func (*StringField_EqFold) isStringField_Operator() {}

func (*StringField_Contains) isStringField_Operator() {}

func (*StringField_HasPrefix) isStringField_Operator() {}

func (*StringField_HasSuffix) isStringField_Operator() {}

func (*StringField_Like) isStringField_Operator() {}

type TimestampField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operator:
	//
	//	*TimestampField_Eq
	//	*TimestampField_Ne
	//	*TimestampField_Gt
	//	*TimestampField_Gte
	//	*TimestampField_Lt
	//	*TimestampField_Lte
	//	*TimestampField_Between
	Operator isTimestampField_Operator `protobuf_oneof:"operator"`
}

func (x *TimestampField) Reset() {
	*x = TimestampField{}
	mi := &file_syralon_entproto_field_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampField) ProtoMessage() {}

func (x *TimestampField) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampField.ProtoReflect.Descriptor instead.
func (*TimestampField) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{19}
}

func (m *TimestampField) GetOperator() isTimestampField_Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (x *TimestampField) GetEq() *timestamppb.Timestamp {
	if x, ok := x.GetOperator().(*TimestampField_Eq); ok {
		return x.Eq
	}
	return nil
}

func (x *TimestampField) GetNe() *timestamppb.Timestamp {
	if x, ok := x.GetOperator().(*TimestampField_Ne); ok {
		return x.Ne
	}
	return nil
}

func (x *TimestampField) GetGt() *timestamppb.Timestamp {
	if x, ok := x.GetOperator().(*TimestampField_Gt); ok {
		return x.Gt
	}
	return nil
}

func (x *TimestampField) GetGte() *timestamppb.Timestamp {
	if x, ok := x.GetOperator().(*TimestampField_Gte); ok {
		return x.Gte
	}
	return nil
}

func (x *TimestampField) GetLt() *timestamppb.Timestamp {
	if x, ok := x.GetOperator().(*TimestampField_Lt); ok {
		return x.Lt
	}
	return nil
}

func (x *TimestampField) GetLte() *timestamppb.Timestamp {
	if x, ok := x.GetOperator().(*TimestampField_Lte); ok {
		return x.Lte
	}
	return nil
}

func (x *TimestampField) GetBetween() *TimestampList {
	if x, ok := x.GetOperator().(*TimestampField_Between); ok {
		return x.Between
	}
	return nil
}

type isTimestampField_Operator interface {
	isTimestampField_Operator()
}

type TimestampField_Eq struct {
	Eq *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=eq,proto3,oneof"`
}

type TimestampField_Ne struct {
	Ne *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ne,proto3,oneof"`
}

type TimestampField_Gt struct {
	Gt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=gt,proto3,oneof"`
}

type TimestampField_Gte struct {
	Gte *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=gte,proto3,oneof"`
}

type TimestampField_Lt struct {
	Lt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=lt,proto3,oneof"`
}

type TimestampField_Lte struct {
	Lte *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=lte,proto3,oneof"`
}

type TimestampField_Between struct {
	Between *TimestampList `protobuf:"bytes,7,opt,name=between,proto3,oneof"`
}

func (*TimestampField_Eq) isTimestampField_Operator() {}

func (*TimestampField_Ne) isTimestampField_Operator() {}

func (*TimestampField_Gt) isTimestampField_Operator() {}

func (*TimestampField_Gte) isTimestampField_Operator() {}

func (*TimestampField_Lt) isTimestampField_Operator() {}

func (*TimestampField_Lte) isTimestampField_Operator() {}

func (*TimestampField_Between) isTimestampField_Operator() {}

type DurationField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Precision PRECISION `protobuf:"varint,1,opt,name=precision,proto3,enum=syralon.entproto.PRECISION" json:"precision,omitempty"`
	// Types that are assignable to Operator:
	//
	//	*DurationField_Eq
	//	*DurationField_Ne
	//	*DurationField_Gt
	//	*DurationField_Gte
	//	*DurationField_Lt
	//	*DurationField_Lte
	//	*DurationField_Between
	Operator isDurationField_Operator `protobuf_oneof:"operator"`
}

func (x *DurationField) Reset() {
	*x = DurationField{}
	mi := &file_syralon_entproto_field_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationField) ProtoMessage() {}

func (x *DurationField) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationField.ProtoReflect.Descriptor instead.
func (*DurationField) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{20}
}

func (x *DurationField) GetPrecision() PRECISION {
	if x != nil {
		return x.Precision
	}
	return PRECISION_MILLISECOND
}

func (m *DurationField) GetOperator() isDurationField_Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (x *DurationField) GetEq() *durationpb.Duration {
	if x, ok := x.GetOperator().(*DurationField_Eq); ok {
		return x.Eq
	}
	return nil
}

func (x *DurationField) GetNe() *durationpb.Duration {
	if x, ok := x.GetOperator().(*DurationField_Ne); ok {
		return x.Ne
	}
	return nil
}

func (x *DurationField) GetGt() *durationpb.Duration {
	if x, ok := x.GetOperator().(*DurationField_Gt); ok {
		return x.Gt
	}
	return nil
}

func (x *DurationField) GetGte() *durationpb.Duration {
	if x, ok := x.GetOperator().(*DurationField_Gte); ok {
		return x.Gte
	}
	return nil
}

func (x *DurationField) GetLt() *durationpb.Duration {
	if x, ok := x.GetOperator().(*DurationField_Lt); ok {
		return x.Lt
	}
	return nil
}

func (x *DurationField) GetLte() *durationpb.Duration {
	if x, ok := x.GetOperator().(*DurationField_Lte); ok {
		return x.Lte
	}
	return nil
}

func (x *DurationField) GetBetween() *DurationList {
	if x, ok := x.GetOperator().(*DurationField_Between); ok {
		return x.Between
	}
	return nil
}

type isDurationField_Operator interface {
	isDurationField_Operator()
}

type DurationField_Eq struct {
	Eq *durationpb.Duration `protobuf:"bytes,2,opt,name=eq,proto3,oneof"`
}

type DurationField_Ne struct {
	Ne *durationpb.Duration `protobuf:"bytes,3,opt,name=ne,proto3,oneof"`
}

type DurationField_Gt struct {
	Gt *durationpb.Duration `protobuf:"bytes,4,opt,name=gt,proto3,oneof"`
}

type DurationField_Gte struct {
	Gte *durationpb.Duration `protobuf:"bytes,5,opt,name=gte,proto3,oneof"`
}

type DurationField_Lt struct {
	Lt *durationpb.Duration `protobuf:"bytes,6,opt,name=lt,proto3,oneof"`
}

type DurationField_Lte struct {
	Lte *durationpb.Duration `protobuf:"bytes,7,opt,name=lte,proto3,oneof"`
}

type DurationField_Between struct {
	Between *DurationList `protobuf:"bytes,8,opt,name=between,proto3,oneof"`
}

func (*DurationField_Eq) isDurationField_Operator() {}

func (*DurationField_Ne) isDurationField_Operator() {}

func (*DurationField_Gt) isDurationField_Operator() {}

func (*DurationField_Gte) isDurationField_Operator() {}

func (*DurationField_Lt) isDurationField_Operator() {}

func (*DurationField_Lte) isDurationField_Operator() {}

func (*DurationField_Between) isDurationField_Operator() {}

type BytesField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operator:
	//
	//	*BytesField_Eq
	//	*BytesField_Ne
	Operator isBytesField_Operator `protobuf_oneof:"operator"`
}

func (x *BytesField) Reset() {
	*x = BytesField{}
	mi := &file_syralon_entproto_field_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesField) ProtoMessage() {}

func (x *BytesField) ProtoReflect() protoreflect.Message {
	mi := &file_syralon_entproto_field_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesField.ProtoReflect.Descriptor instead.
func (*BytesField) Descriptor() ([]byte, []int) {
	return file_syralon_entproto_field_proto_rawDescGZIP(), []int{21}
}

func (m *BytesField) GetOperator() isBytesField_Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (x *BytesField) GetEq() []byte {
	if x, ok := x.GetOperator().(*BytesField_Eq); ok {
		return x.Eq
	}
	return nil
}

func (x *BytesField) GetNe() []byte {
	if x, ok := x.GetOperator().(*BytesField_Ne); ok {
		return x.Ne
	}
	return nil
}

type isBytesField_Operator interface {
	isBytesField_Operator()
}

type BytesField_Eq struct {
	Eq []byte `protobuf:"bytes,1,opt,name=eq,proto3,oneof"`
}

type BytesField_Ne struct {
	Ne []byte `protobuf:"bytes,2,opt,name=ne,proto3,oneof"`
}

func (*BytesField_Eq) isBytesField_Operator() {}

func (*BytesField_Ne) isBytesField_Operator() {}

var File_syralon_entproto_field_proto protoreflect.FileDescriptor

var file_syralon_entproto_field_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1f, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x22, 0x1f, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x0a, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x0a, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x04, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x1f, 0x0a, 0x09, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x02, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x0a, 0x44, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x1e, 0x0a, 0x08, 0x42, 0x6f,
	0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x0a, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x3f, 0x0a, 0x0d,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x3d, 0x0a,
	0x0c, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x1f, 0x0a, 0x09,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xa6, 0x02,
	0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x02,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x02, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x6e, 0x65,
	0x12, 0x10, 0x0a, 0x02, 0x67, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02,
	0x67, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x67, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x00, 0x52, 0x03, 0x67, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6c, 0x74, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x07,
	0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x62, 0x65,
	0x74, 0x77, 0x65, 0x65, 0x6e, 0x12, 0x2d, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x02, 0x69, 0x6e, 0x12, 0x34, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x5f, 0x69, 0x6e, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65,
	0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4c, 0x69, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x49, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xa6, 0x02, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x36, 0x34,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x02, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x02, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x02, 0x6e, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x02, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x67, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x02, 0x67, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x67,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x67, 0x74, 0x65, 0x12,
	0x10, 0x0a, 0x02, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x02, 0x6c,
	0x74, 0x12, 0x12, 0x0a, 0x03, 0x6c, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00,
	0x52, 0x03, 0x6c, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e,
	0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x12, 0x2d,
	0x0a, 0x02, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x79, 0x72,
	0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x34, 0x0a,
	0x06, 0x6e, 0x6f, 0x74, 0x5f, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x6e, 0x6f,
	0x74, 0x49, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22,
	0xaa, 0x02, 0x0a, 0x0b, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x10, 0x0a, 0x02, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x02, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x02, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52,
	0x02, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x67, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48,
	0x00, 0x52, 0x02, 0x67, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x67, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x48, 0x00, 0x52, 0x03, 0x67, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x6c, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x02, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6c,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x74, 0x65, 0x12,
	0x38, 0x0a, 0x07, 0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x07, 0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x02, 0x69, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e,
	0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x35, 0x0a, 0x06, 0x6e, 0x6f, 0x74,
	0x5f, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x79, 0x72, 0x61,
	0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x69, 0x6e,
	0x74, 0x33, 0x32, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x49, 0x6e,
	0x42, 0x0a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xaa, 0x02, 0x0a,
	0x0b, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x02,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x02, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x02, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x02, 0x6e, 0x65,
	0x12, 0x10, 0x0a, 0x02, 0x67, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x02,
	0x67, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x67, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x48,
	0x00, 0x52, 0x03, 0x67, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x48, 0x00, 0x52, 0x02, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6c, 0x74, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x74, 0x65, 0x12, 0x38, 0x0a, 0x07,
	0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x62,
	0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x4c, 0x69, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x35, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x5f, 0x69, 0x6e,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e,
	0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x49, 0x6e, 0x42, 0x0a, 0x0a,
	0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xa6, 0x02, 0x0a, 0x0a, 0x46, 0x6c,
	0x6f, 0x61, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x02, 0x65, 0x71, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x02, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x02, 0x6e, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x02, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x02,
	0x67, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x02, 0x67, 0x74, 0x12, 0x12,
	0x0a, 0x03, 0x67, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x03, 0x67,
	0x74, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00,
	0x52, 0x02, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6c, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x02, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x62, 0x65, 0x74, 0x77,
	0x65, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x79, 0x72, 0x61,
	0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x62, 0x65, 0x74, 0x77, 0x65, 0x65,
	0x6e, 0x12, 0x2d, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x02, 0x69, 0x6e,
	0x12, 0x34, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x5f, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x05, 0x6e, 0x6f, 0x74, 0x49, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x22, 0xaa, 0x02, 0x0a, 0x0b, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x10, 0x0a, 0x02, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00,
	0x52, 0x02, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x02, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x48, 0x00, 0x52, 0x02, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x67, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x48, 0x00, 0x52, 0x02, 0x67, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x67, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x03, 0x67, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x02,
	0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x02, 0x6c, 0x74, 0x12, 0x12,
	0x0a, 0x03, 0x6c, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x03, 0x6c,
	0x74, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e,
	0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x07, 0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x02,
	0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c,
	0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x35, 0x0a, 0x06,
	0x6e, 0x6f, 0x74, 0x5f, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73,
	0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x6e, 0x6f,
	0x74, 0x49, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22,
	0x3b, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x02,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x02, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x02, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x02, 0x6e, 0x65,
	0x42, 0x0a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xbb, 0x03, 0x0a,
	0x0b, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x02,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x02, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x6e, 0x65,
	0x12, 0x10, 0x0a, 0x02, 0x67, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02,
	0x67, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x67, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x03, 0x67, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6c, 0x74, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x74, 0x65, 0x12, 0x38, 0x0a, 0x07,
	0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x62,
	0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x35, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x5f, 0x69, 0x6e,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e,
	0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x49, 0x6e, 0x12, 0x19, 0x0a,
	0x07, 0x65, 0x71, 0x5f, 0x66, 0x6f, 0x6c, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x65, 0x71, 0x46, 0x6f, 0x6c, 0x64, 0x12, 0x1c, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0a, 0x68, 0x61, 0x73, 0x5f, 0x70, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x68, 0x61,
	0x73, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x1f, 0x0a, 0x0a, 0x68, 0x61, 0x73, 0x5f, 0x73,
	0x75, 0x66, 0x66, 0x69, 0x78, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x68,
	0x61, 0x73, 0x53, 0x75, 0x66, 0x66, 0x69, 0x78, 0x12, 0x14, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x42, 0x0a,
	0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xf1, 0x02, 0x0a, 0x0e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2c, 0x0a,
	0x02, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x02, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x02, 0x6e,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x02, 0x6e, 0x65, 0x12, 0x2c, 0x0a, 0x02, 0x67, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x48, 0x00, 0x52, 0x02, 0x67, 0x74, 0x12, 0x2e, 0x0a, 0x03, 0x67, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x48, 0x00, 0x52, 0x03, 0x67, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x02, 0x6c, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48,
	0x00, 0x52, 0x02, 0x6c, 0x74, 0x12, 0x2e, 0x0a, 0x03, 0x6c, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00,
	0x52, 0x03, 0x6c, 0x74, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e,
	0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x62, 0x65, 0x74, 0x77, 0x65,
	0x65, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xa4,
	0x03, 0x0a, 0x0d, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x39, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e,
	0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x52, 0x45, 0x43, 0x49, 0x53, 0x49, 0x4f, 0x4e,
	0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x02, 0x65,
	0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x02, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x02, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x02, 0x6e, 0x65, 0x12, 0x2b, 0x0a, 0x02, 0x67, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x02,
	0x67, 0x74, 0x12, 0x2d, 0x0a, 0x03, 0x67, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x67, 0x74,
	0x65, 0x12, 0x2b, 0x0a, 0x02, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x02, 0x6c, 0x74, 0x12, 0x2d,
	0x0a, 0x03, 0x6c, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x74, 0x65, 0x12, 0x3a, 0x0a,
	0x07, 0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x07, 0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x3c, 0x0a, 0x0a, 0x42, 0x79, 0x74, 0x65, 0x73, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x02, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x02, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x02, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x02, 0x6e, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2a, 0x47, 0x0a, 0x09, 0x50, 0x52, 0x45, 0x43, 0x49, 0x53, 0x49, 0x4f, 0x4e,
	0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x49, 0x4c, 0x4c, 0x49, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x4d, 0x49, 0x4e, 0x55, 0x54, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x55,
	0x52, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x41, 0x59, 0x10, 0x04, 0x42, 0x40, 0x5a, 0x3e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x72, 0x61, 0x6c,
	0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x74, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x65, 0x6e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_syralon_entproto_field_proto_rawDescOnce sync.Once
	file_syralon_entproto_field_proto_rawDescData = file_syralon_entproto_field_proto_rawDesc
)

func file_syralon_entproto_field_proto_rawDescGZIP() []byte {
	file_syralon_entproto_field_proto_rawDescOnce.Do(func() {
		file_syralon_entproto_field_proto_rawDescData = protoimpl.X.CompressGZIP(file_syralon_entproto_field_proto_rawDescData)
	})
	return file_syralon_entproto_field_proto_rawDescData
}

var file_syralon_entproto_field_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_syralon_entproto_field_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_syralon_entproto_field_proto_goTypes = []any{
	(PRECISION)(0),                // 0: syralon.entproto.PRECISION
	(*Int32List)(nil),             // 1: syralon.entproto.Int32List
	(*Int64List)(nil),             // 2: syralon.entproto.Int64List
	(*Uint32List)(nil),            // 3: syralon.entproto.Uint32List
	(*Uint64List)(nil),            // 4: syralon.entproto.Uint64List
	(*FloatList)(nil),             // 5: syralon.entproto.FloatList
	(*DoubleList)(nil),            // 6: syralon.entproto.DoubleList
	(*BoolList)(nil),              // 7: syralon.entproto.BoolList
	(*StringList)(nil),            // 8: syralon.entproto.StringList
	(*TimestampList)(nil),         // 9: syralon.entproto.TimestampList
	(*DurationList)(nil),          // 10: syralon.entproto.DurationList
	(*BytesList)(nil),             // 11: syralon.entproto.BytesList
	(*Int32Field)(nil),            // 12: syralon.entproto.Int32Field
	(*Int64Field)(nil),            // 13: syralon.entproto.Int64Field
	(*Uint32Field)(nil),           // 14: syralon.entproto.Uint32Field
	(*Uint64Field)(nil),           // 15: syralon.entproto.Uint64Field
	(*FloatField)(nil),            // 16: syralon.entproto.FloatField
	(*DoubleField)(nil),           // 17: syralon.entproto.DoubleField
	(*BoolField)(nil),             // 18: syralon.entproto.BoolField
	(*StringField)(nil),           // 19: syralon.entproto.StringField
	(*TimestampField)(nil),        // 20: syralon.entproto.TimestampField
	(*DurationField)(nil),         // 21: syralon.entproto.DurationField
	(*BytesField)(nil),            // 22: syralon.entproto.BytesField
	(*timestamppb.Timestamp)(nil), // 23: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 24: google.protobuf.Duration
}
var file_syralon_entproto_field_proto_depIdxs = []int32{
	23, // 0: syralon.entproto.TimestampList.list:type_name -> google.protobuf.Timestamp
	24, // 1: syralon.entproto.DurationList.list:type_name -> google.protobuf.Duration
	1,  // 2: syralon.entproto.Int32Field.between:type_name -> syralon.entproto.Int32List
	1,  // 3: syralon.entproto.Int32Field.in:type_name -> syralon.entproto.Int32List
	1,  // 4: syralon.entproto.Int32Field.not_in:type_name -> syralon.entproto.Int32List
	2,  // 5: syralon.entproto.Int64Field.between:type_name -> syralon.entproto.Int64List
	2,  // 6: syralon.entproto.Int64Field.in:type_name -> syralon.entproto.Int64List
	2,  // 7: syralon.entproto.Int64Field.not_in:type_name -> syralon.entproto.Int64List
	3,  // 8: syralon.entproto.Uint32Field.between:type_name -> syralon.entproto.Uint32List
	3,  // 9: syralon.entproto.Uint32Field.in:type_name -> syralon.entproto.Uint32List
	3,  // 10: syralon.entproto.Uint32Field.not_in:type_name -> syralon.entproto.Uint32List
	4,  // 11: syralon.entproto.Uint64Field.between:type_name -> syralon.entproto.Uint64List
	4,  // 12: syralon.entproto.Uint64Field.in:type_name -> syralon.entproto.Uint64List
	4,  // 13: syralon.entproto.Uint64Field.not_in:type_name -> syralon.entproto.Uint64List
	5,  // 14: syralon.entproto.FloatField.between:type_name -> syralon.entproto.FloatList
	5,  // 15: syralon.entproto.FloatField.in:type_name -> syralon.entproto.FloatList
	5,  // 16: syralon.entproto.FloatField.not_in:type_name -> syralon.entproto.FloatList
	6,  // 17: syralon.entproto.DoubleField.between:type_name -> syralon.entproto.DoubleList
	6,  // 18: syralon.entproto.DoubleField.in:type_name -> syralon.entproto.DoubleList
	6,  // 19: syralon.entproto.DoubleField.not_in:type_name -> syralon.entproto.DoubleList
	8,  // 20: syralon.entproto.StringField.between:type_name -> syralon.entproto.StringList
	8,  // 21: syralon.entproto.StringField.in:type_name -> syralon.entproto.StringList
	8,  // 22: syralon.entproto.StringField.not_in:type_name -> syralon.entproto.StringList
	23, // 23: syralon.entproto.TimestampField.eq:type_name -> google.protobuf.Timestamp
	23, // 24: syralon.entproto.TimestampField.ne:type_name -> google.protobuf.Timestamp
	23, // 25: syralon.entproto.TimestampField.gt:type_name -> google.protobuf.Timestamp
	23, // 26: syralon.entproto.TimestampField.gte:type_name -> google.protobuf.Timestamp
	23, // 27: syralon.entproto.TimestampField.lt:type_name -> google.protobuf.Timestamp
	23, // 28: syralon.entproto.TimestampField.lte:type_name -> google.protobuf.Timestamp
	9,  // 29: syralon.entproto.TimestampField.between:type_name -> syralon.entproto.TimestampList
	0,  // 30: syralon.entproto.DurationField.precision:type_name -> syralon.entproto.PRECISION
	24, // 31: syralon.entproto.DurationField.eq:type_name -> google.protobuf.Duration
	24, // 32: syralon.entproto.DurationField.ne:type_name -> google.protobuf.Duration
	24, // 33: syralon.entproto.DurationField.gt:type_name -> google.protobuf.Duration
	24, // 34: syralon.entproto.DurationField.gte:type_name -> google.protobuf.Duration
	24, // 35: syralon.entproto.DurationField.lt:type_name -> google.protobuf.Duration
	24, // 36: syralon.entproto.DurationField.lte:type_name -> google.protobuf.Duration
	10, // 37: syralon.entproto.DurationField.between:type_name -> syralon.entproto.DurationList
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_syralon_entproto_field_proto_init() }
func file_syralon_entproto_field_proto_init() {
	if File_syralon_entproto_field_proto != nil {
		return
	}
	file_syralon_entproto_field_proto_msgTypes[11].OneofWrappers = []any{
		(*Int32Field_Eq)(nil),
		(*Int32Field_Ne)(nil),
		(*Int32Field_Gt)(nil),
		(*Int32Field_Gte)(nil),
		(*Int32Field_Lt)(nil),
		(*Int32Field_Lte)(nil),
		(*Int32Field_Between)(nil),
		(*Int32Field_In)(nil),
		(*Int32Field_NotIn)(nil),
	}
	file_syralon_entproto_field_proto_msgTypes[12].OneofWrappers = []any{
		(*Int64Field_Eq)(nil),
		(*Int64Field_Ne)(nil),
		(*Int64Field_Gt)(nil),
		(*Int64Field_Gte)(nil),
		(*Int64Field_Lt)(nil),
		(*Int64Field_Lte)(nil),
		(*Int64Field_Between)(nil),
		(*Int64Field_In)(nil),
		(*Int64Field_NotIn)(nil),
	}
	file_syralon_entproto_field_proto_msgTypes[13].OneofWrappers = []any{
		(*Uint32Field_Eq)(nil),
		(*Uint32Field_Ne)(nil),
		(*Uint32Field_Gt)(nil),
		(*Uint32Field_Gte)(nil),
		(*Uint32Field_Lt)(nil),
		(*Uint32Field_Lte)(nil),
		(*Uint32Field_Between)(nil),
		(*Uint32Field_In)(nil),
		(*Uint32Field_NotIn)(nil),
	}
	file_syralon_entproto_field_proto_msgTypes[14].OneofWrappers = []any{
		(*Uint64Field_Eq)(nil),
		(*Uint64Field_Ne)(nil),
		(*Uint64Field_Gt)(nil),
		(*Uint64Field_Gte)(nil),
		(*Uint64Field_Lt)(nil),
		(*Uint64Field_Lte)(nil),
		(*Uint64Field_Between)(nil),
		(*Uint64Field_In)(nil),
		(*Uint64Field_NotIn)(nil),
	}
	file_syralon_entproto_field_proto_msgTypes[15].OneofWrappers = []any{
		(*FloatField_Eq)(nil),
		(*FloatField_Ne)(nil),
		(*FloatField_Gt)(nil),
		(*FloatField_Gte)(nil),
		(*FloatField_Lt)(nil),
		(*FloatField_Lte)(nil),
		(*FloatField_Between)(nil),
		(*FloatField_In)(nil),
		(*FloatField_NotIn)(nil),
	}
	file_syralon_entproto_field_proto_msgTypes[16].OneofWrappers = []any{
		(*DoubleField_Eq)(nil),
		(*DoubleField_Ne)(nil),
		(*DoubleField_Gt)(nil),
		(*DoubleField_Gte)(nil),
		(*DoubleField_Lt)(nil),
		(*DoubleField_Lte)(nil),
		(*DoubleField_Between)(nil),
		(*DoubleField_In)(nil),
		(*DoubleField_NotIn)(nil),
	}
	file_syralon_entproto_field_proto_msgTypes[17].OneofWrappers = []any{
		(*BoolField_Eq)(nil),
		(*BoolField_Ne)(nil),
	}
	file_syralon_entproto_field_proto_msgTypes[18].OneofWrappers = []any{
		(*StringField_Eq)(nil),
		(*StringField_Ne)(nil),
		(*StringField_Gt)(nil),
		(*StringField_Gte)(nil),
		(*StringField_Lt)(nil),
		(*StringField_Lte)(nil),
		(*StringField_Between)(nil),
		(*StringField_In)(nil),
		(*StringField_NotIn)(nil),
		(*StringField_EqFold)(nil),
		(*StringField_Contains)(nil),
		(*StringField_HasPrefix)(nil),
		(*StringField_HasSuffix)(nil),
		(*StringField_Like)(nil),
	}
	file_syralon_entproto_field_proto_msgTypes[19].OneofWrappers = []any{
		(*TimestampField_Eq)(nil),
		(*TimestampField_Ne)(nil),
		(*TimestampField_Gt)(nil),
		(*TimestampField_Gte)(nil),
		(*TimestampField_Lt)(nil),
		(*TimestampField_Lte)(nil),
		(*TimestampField_Between)(nil),
	}
	file_syralon_entproto_field_proto_msgTypes[20].OneofWrappers = []any{
		(*DurationField_Eq)(nil),
		(*DurationField_Ne)(nil),
		(*DurationField_Gt)(nil),
		(*DurationField_Gte)(nil),
		(*DurationField_Lt)(nil),
		(*DurationField_Lte)(nil),
		(*DurationField_Between)(nil),
	}
	file_syralon_entproto_field_proto_msgTypes[21].OneofWrappers = []any{
		(*BytesField_Eq)(nil),
		(*BytesField_Ne)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_syralon_entproto_field_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_syralon_entproto_field_proto_goTypes,
		DependencyIndexes: file_syralon_entproto_field_proto_depIdxs,
		EnumInfos:         file_syralon_entproto_field_proto_enumTypes,
		MessageInfos:      file_syralon_entproto_field_proto_msgTypes,
	}.Build()
	File_syralon_entproto_field_proto = out.File
	file_syralon_entproto_field_proto_rawDesc = nil
	file_syralon_entproto_field_proto_goTypes = nil
	file_syralon_entproto_field_proto_depIdxs = nil
}
