// Code generated by chocoproto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/example/ent_service.proto

package example

import (
	_ "github.com/google/gnostic/openapiv3"
	entproto "github.com/syralon/entc-gen-go/proto/syralon/entproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupOrder int32

const (
	GroupOrder_GROUP_ORDER_BY_ID         GroupOrder = 0
	GroupOrder_GROUP_ORDER_BY_CREATED_AT GroupOrder = 1
	GroupOrder_GROUP_ORDER_BY_UPDATED_AT GroupOrder = 2
)

// Enum value maps for GroupOrder.
var (
	GroupOrder_name = map[int32]string{
		0: "GROUP_ORDER_BY_ID",
		1: "GROUP_ORDER_BY_CREATED_AT",
		2: "GROUP_ORDER_BY_UPDATED_AT",
	}
	GroupOrder_value = map[string]int32{
		"GROUP_ORDER_BY_ID":         0,
		"GROUP_ORDER_BY_CREATED_AT": 1,
		"GROUP_ORDER_BY_UPDATED_AT": 2,
	}
)

func (x GroupOrder) Enum() *GroupOrder {
	p := new(GroupOrder)
	*p = x
	return p
}

func (x GroupOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_example_ent_service_proto_enumTypes[0].Descriptor()
}

func (GroupOrder) Type() protoreflect.EnumType {
	return &file_proto_example_ent_service_proto_enumTypes[0]
}

func (x GroupOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupOrder.Descriptor instead.
func (GroupOrder) EnumDescriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{0}
}

type UserOrder int32

const (
	UserOrder_USER_ORDER_BY_ID         UserOrder = 0
	UserOrder_USER_ORDER_BY_CREATED_AT UserOrder = 1
	UserOrder_USER_ORDER_BY_GROUP_ID   UserOrder = 2
)

// Enum value maps for UserOrder.
var (
	UserOrder_name = map[int32]string{
		0: "USER_ORDER_BY_ID",
		1: "USER_ORDER_BY_CREATED_AT",
		2: "USER_ORDER_BY_GROUP_ID",
	}
	UserOrder_value = map[string]int32{
		"USER_ORDER_BY_ID":         0,
		"USER_ORDER_BY_CREATED_AT": 1,
		"USER_ORDER_BY_GROUP_ID":   2,
	}
)

func (x UserOrder) Enum() *UserOrder {
	p := new(UserOrder)
	*p = x
	return p
}

func (x UserOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_example_ent_service_proto_enumTypes[1].Descriptor()
}

func (UserOrder) Type() protoreflect.EnumType {
	return &file_proto_example_ent_service_proto_enumTypes[1]
}

func (x UserOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserOrder.Descriptor instead.
func (UserOrder) EnumDescriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{1}
}

type GroupOptions struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            *entproto.Int64Field     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *entproto.StringField    `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	CreatedAt     *entproto.TimestampField `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt     *entproto.TimestampField `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	GroupUsers    *UserOptions             `protobuf:"bytes,5,opt,name=group_users,json=groupUsers,proto3" json:"group_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupOptions) Reset() {
	*x = GroupOptions{}
	mi := &file_proto_example_ent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupOptions) ProtoMessage() {}

func (x *GroupOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupOptions.ProtoReflect.Descriptor instead.
func (*GroupOptions) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{0}
}

func (x *GroupOptions) GetId() *entproto.Int64Field {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GroupOptions) GetName() *entproto.StringField {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *GroupOptions) GetCreatedAt() *entproto.TimestampField {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GroupOptions) GetUpdatedAt() *entproto.TimestampField {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GroupOptions) GetGroupUsers() *UserOptions {
	if x != nil {
		return x.GroupUsers
	}
	return nil
}

type UserOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *entproto.Int64Field   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The user name
	Name *entproto.StringField `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// The created time
	CreatedAt *entproto.TimestampField `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	// The latest update time
	UpdatedAt     *entproto.TimestampField `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	GroupId       *entproto.Int64Field     `protobuf:"bytes,5,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Status        *entproto.Int32Field     `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	UserGroups    *GroupOptions            `protobuf:"bytes,7,opt,name=user_groups,json=userGroups,proto3" json:"user_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOptions) Reset() {
	*x = UserOptions{}
	mi := &file_proto_example_ent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOptions) ProtoMessage() {}

func (x *UserOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOptions.ProtoReflect.Descriptor instead.
func (*UserOptions) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserOptions) GetId() *entproto.Int64Field {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UserOptions) GetName() *entproto.StringField {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UserOptions) GetCreatedAt() *entproto.TimestampField {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserOptions) GetUpdatedAt() *entproto.TimestampField {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserOptions) GetGroupId() *entproto.Int64Field {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *UserOptions) GetStatus() *entproto.Int32Field {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UserOptions) GetUserGroups() *GroupOptions {
	if x != nil {
		return x.UserGroups
	}
	return nil
}

type GroupUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	GroupUsers    *UserUpdate            `protobuf:"bytes,2,opt,name=group_users,json=groupUsers,proto3" json:"group_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUpdate) Reset() {
	*x = GroupUpdate{}
	mi := &file_proto_example_ent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUpdate) ProtoMessage() {}

func (x *GroupUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUpdate.ProtoReflect.Descriptor instead.
func (*GroupUpdate) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{2}
}

func (x *GroupUpdate) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GroupUpdate) GetGroupUsers() *UserUpdate {
	if x != nil {
		return x.GroupUsers
	}
	return nil
}

type UserUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user name
	Name          *string      `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	GroupId       *int64       `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Status        *int32       `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	UserGroups    *GroupUpdate `protobuf:"bytes,4,opt,name=user_groups,json=userGroups,proto3" json:"user_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdate) Reset() {
	*x = UserUpdate{}
	mi := &file_proto_example_ent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdate) ProtoMessage() {}

func (x *UserUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdate.ProtoReflect.Descriptor instead.
func (*UserUpdate) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{3}
}

func (x *UserUpdate) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UserUpdate) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *UserUpdate) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *UserUpdate) GetUserGroups() *GroupUpdate {
	if x != nil {
		return x.UserGroups
	}
	return nil
}

type ListGroupOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	By            GroupOrder             `protobuf:"varint,1,opt,name=by,proto3,enum=proto.example.GroupOrder" json:"by,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupOrder) Reset() {
	*x = ListGroupOrder{}
	mi := &file_proto_example_ent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupOrder) ProtoMessage() {}

func (x *ListGroupOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupOrder.ProtoReflect.Descriptor instead.
func (*ListGroupOrder) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListGroupOrder) GetBy() GroupOrder {
	if x != nil {
		return x.By
	}
	return GroupOrder_GROUP_ORDER_BY_ID
}

func (x *ListGroupOrder) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type ListUserOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	By            UserOrder              `protobuf:"varint,1,opt,name=by,proto3,enum=proto.example.UserOrder" json:"by,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserOrder) Reset() {
	*x = ListUserOrder{}
	mi := &file_proto_example_ent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOrder) ProtoMessage() {}

func (x *ListUserOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOrder.ProtoReflect.Descriptor instead.
func (*ListUserOrder) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserOrder) GetBy() UserOrder {
	if x != nil {
		return x.By
	}
	return UserOrder_USER_ORDER_BY_ID
}

func (x *ListUserOrder) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Group                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetGroupResponse) GetData() *Group {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *User                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *GroupOptions          `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Orders        []*ListGroupOrder      `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	Paginator     *entproto.Paginator    `protobuf:"bytes,3,opt,name=paginator,proto3" json:"paginator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupRequest) Reset() {
	*x = ListGroupRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupRequest) ProtoMessage() {}

func (x *ListGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupRequest.ProtoReflect.Descriptor instead.
func (*ListGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListGroupRequest) GetOptions() *GroupOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListGroupRequest) GetOrders() []*ListGroupOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListGroupRequest) GetPaginator() *entproto.Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

type ListGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Group               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupResponse) Reset() {
	*x = ListGroupResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupResponse) ProtoMessage() {}

func (x *ListGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupResponse.ProtoReflect.Descriptor instead.
func (*ListGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListGroupResponse) GetData() []*Group {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *UserOptions           `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Orders        []*ListUserOrder       `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	Paginator     *entproto.Paginator    `protobuf:"bytes,3,opt,name=paginator,proto3" json:"paginator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRequest) Reset() {
	*x = ListUserRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRequest) ProtoMessage() {}

func (x *ListUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRequest.ProtoReflect.Descriptor instead.
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserRequest) GetOptions() *UserOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListUserRequest) GetOrders() []*ListUserOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListUserRequest) GetPaginator() *entproto.Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

type ListUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*User                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserResponse) Reset() {
	*x = ListUserResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserResponse) ProtoMessage() {}

func (x *ListUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserResponse.ProtoReflect.Descriptor instead.
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListUserResponse) GetData() []*User {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The user name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The created time
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The latest update time
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	GroupId       int64                  `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	UserGroups    []*Group               `protobuf:"bytes,7,rep,name=user_groups,json=userGroups,proto3" json:"user_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{14}
}

func (x *CreateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CreateUserRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CreateUserRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateUserRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateUserRequest) GetUserGroups() []*Group {
	if x != nil {
		return x.UserGroups
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateUserResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Update        *UserUpdate            `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetUpdate() *UserUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{17}
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{19}
}

type SetUserGroupIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Options       *UserOptions           `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	GroupId       int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserGroupIdRequest) Reset() {
	*x = SetUserGroupIdRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserGroupIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserGroupIdRequest) ProtoMessage() {}

func (x *SetUserGroupIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserGroupIdRequest.ProtoReflect.Descriptor instead.
func (*SetUserGroupIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{20}
}

func (x *SetUserGroupIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetUserGroupIdRequest) GetOptions() *UserOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SetUserGroupIdRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type SetUserGroupIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          int32                  `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserGroupIdResponse) Reset() {
	*x = SetUserGroupIdResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserGroupIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserGroupIdResponse) ProtoMessage() {}

func (x *SetUserGroupIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserGroupIdResponse.ProtoReflect.Descriptor instead.
func (*SetUserGroupIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{21}
}

func (x *SetUserGroupIdResponse) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type SetUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Options       *UserOptions           `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserStatusRequest) Reset() {
	*x = SetUserStatusRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserStatusRequest) ProtoMessage() {}

func (x *SetUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserStatusRequest.ProtoReflect.Descriptor instead.
func (*SetUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{22}
}

func (x *SetUserStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetUserStatusRequest) GetOptions() *UserOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SetUserStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type SetUserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          int32                  `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserStatusResponse) Reset() {
	*x = SetUserStatusResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserStatusResponse) ProtoMessage() {}

func (x *SetUserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserStatusResponse.ProtoReflect.Descriptor instead.
func (*SetUserStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{23}
}

func (x *SetUserStatusResponse) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ListUserUserGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Options       *GroupOptions          `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Orders        []*ListGroupOrder      `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	Paginator     *entproto.Paginator    `protobuf:"bytes,4,opt,name=paginator,proto3" json:"paginator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserUserGroupsRequest) Reset() {
	*x = ListUserUserGroupsRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserUserGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserUserGroupsRequest) ProtoMessage() {}

func (x *ListUserUserGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserUserGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListUserUserGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{24}
}

func (x *ListUserUserGroupsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListUserUserGroupsRequest) GetOptions() *GroupOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListUserUserGroupsRequest) GetOrders() []*ListGroupOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListUserUserGroupsRequest) GetPaginator() *entproto.Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

var File_proto_example_ent_service_proto protoreflect.FileDescriptor

const file_proto_example_ent_service_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/example/ent_service.proto\x12\rproto.example\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bopenapiv3/annotations.proto\x1a\x17proto/example/ent.proto\x1a\x1csyralon/entproto/field.proto\x1a syralon/entproto/paginator.proto\"\xe4\x02\n" +
	"\fGroupOptions\x12,\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.syralon.entproto.Int64FieldR\x02id\x126\n" +
	"\x04name\x18\x02 \x01(\v2\x1d.syralon.entproto.StringFieldH\x00R\x04name\x88\x01\x01\x12D\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2 .syralon.entproto.TimestampFieldH\x01R\tcreatedAt\x88\x01\x01\x12D\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2 .syralon.entproto.TimestampFieldH\x02R\tupdatedAt\x88\x01\x01\x12;\n" +
	"\vgroup_users\x18\x05 \x01(\v2\x1a.proto.example.UserOptionsR\n" +
	"groupUsersB\a\n" +
	"\x05_nameB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_at\"\x85\x04\n" +
	"\vUserOptions\x12,\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.syralon.entproto.Int64FieldR\x02id\x12F\n" +
	"\x04name\x18\x02 \x01(\v2\x1d.syralon.entproto.StringFieldB\x0e\xbaG\v\x92\x02\bThe nameH\x00R\x04name\x88\x01\x01\x12D\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2 .syralon.entproto.TimestampFieldH\x01R\tcreatedAt\x88\x01\x01\x12D\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2 .syralon.entproto.TimestampFieldH\x02R\tupdatedAt\x88\x01\x01\x12<\n" +
	"\bgroup_id\x18\x05 \x01(\v2\x1c.syralon.entproto.Int64FieldH\x03R\agroupId\x88\x01\x01\x129\n" +
	"\x06status\x18\x06 \x01(\v2\x1c.syralon.entproto.Int32FieldH\x04R\x06status\x88\x01\x01\x12<\n" +
	"\vuser_groups\x18\a \x01(\v2\x1b.proto.example.GroupOptionsR\n" +
	"userGroupsB\a\n" +
	"\x05_nameB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_atB\v\n" +
	"\t_group_idB\t\n" +
	"\a_status\"k\n" +
	"\vGroupUpdate\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12:\n" +
	"\vgroup_users\x18\x02 \x01(\v2\x19.proto.example.UserUpdateR\n" +
	"groupUsersB\a\n" +
	"\x05_name\"\xd0\x01\n" +
	"\n" +
	"UserUpdate\x12'\n" +
	"\x04name\x18\x01 \x01(\tB\x0e\xbaG\v\x92\x02\bThe nameH\x00R\x04name\x88\x01\x01\x12\x1e\n" +
	"\bgroup_id\x18\x02 \x01(\x03H\x01R\agroupId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x02R\x06status\x88\x01\x01\x12;\n" +
	"\vuser_groups\x18\x04 \x01(\v2\x1a.proto.example.GroupUpdateR\n" +
	"userGroupsB\a\n" +
	"\x05_nameB\v\n" +
	"\t_group_idB\t\n" +
	"\a_status\"O\n" +
	"\x0eListGroupOrder\x12)\n" +
	"\x02by\x18\x01 \x01(\x0e2\x19.proto.example.GroupOrderR\x02by\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"M\n" +
	"\rListUserOrder\x12(\n" +
	"\x02by\x18\x01 \x01(\x0e2\x18.proto.example.UserOrderR\x02by\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"!\n" +
	"\x0fGetGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"<\n" +
	"\x10GetGroupResponse\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.proto.example.GroupR\x04data\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x0fGetUserResponse\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.proto.example.UserR\x04data\"\xbb\x01\n" +
	"\x10ListGroupRequest\x125\n" +
	"\aoptions\x18\x01 \x01(\v2\x1b.proto.example.GroupOptionsR\aoptions\x125\n" +
	"\x06orders\x18\x02 \x03(\v2\x1d.proto.example.ListGroupOrderR\x06orders\x129\n" +
	"\tpaginator\x18\x03 \x01(\v2\x1b.syralon.entproto.PaginatorR\tpaginator\"=\n" +
	"\x11ListGroupResponse\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.proto.example.GroupR\x04data\"\xb8\x01\n" +
	"\x0fListUserRequest\x124\n" +
	"\aoptions\x18\x01 \x01(\v2\x1a.proto.example.UserOptionsR\aoptions\x124\n" +
	"\x06orders\x18\x02 \x03(\v2\x1c.proto.example.ListUserOrderR\x06orders\x129\n" +
	"\tpaginator\x18\x03 \x01(\v2\x1b.syralon.entproto.PaginatorR\tpaginator\";\n" +
	"\x10ListUserResponse\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.proto.example.UserR\x04data\"\xa7\x02\n" +
	"\x11CreateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\x04name\x18\x02 \x01(\tB\x0e\xbaG\v\x92\x02\bThe nameR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x125\n" +
	"\vuser_groups\x18\a \x03(\v2\x14.proto.example.GroupR\n" +
	"userGroups\"$\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"V\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x121\n" +
	"\x06update\x18\x02 \x01(\v2\x19.proto.example.UserUpdateR\x06update\"\x14\n" +
	"\x12UpdateUserResponse\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteUserResponse\"x\n" +
	"\x15SetUserGroupIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x124\n" +
	"\aoptions\x18\x02 \x01(\v2\x1a.proto.example.UserOptionsR\aoptions\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\",\n" +
	"\x16SetUserGroupIdResponse\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x05R\x04rows\"t\n" +
	"\x14SetUserStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x124\n" +
	"\aoptions\x18\x02 \x01(\v2\x1a.proto.example.UserOptionsR\aoptions\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"+\n" +
	"\x15SetUserStatusResponse\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x05R\x04rows\"\xd4\x01\n" +
	"\x19ListUserUserGroupsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x125\n" +
	"\aoptions\x18\x02 \x01(\v2\x1b.proto.example.GroupOptionsR\aoptions\x125\n" +
	"\x06orders\x18\x03 \x03(\v2\x1d.proto.example.ListGroupOrderR\x06orders\x129\n" +
	"\tpaginator\x18\x04 \x01(\v2\x1b.syralon.entproto.PaginatorR\tpaginator*a\n" +
	"\n" +
	"GroupOrder\x12\x15\n" +
	"\x11GROUP_ORDER_BY_ID\x10\x00\x12\x1d\n" +
	"\x19GROUP_ORDER_BY_CREATED_AT\x10\x01\x12\x1d\n" +
	"\x19GROUP_ORDER_BY_UPDATED_AT\x10\x02*[\n" +
	"\tUserOrder\x12\x14\n" +
	"\x10USER_ORDER_BY_ID\x10\x00\x12\x1c\n" +
	"\x18USER_ORDER_BY_CREATED_AT\x10\x01\x12\x1a\n" +
	"\x16USER_ORDER_BY_GROUP_ID\x10\x022\xcc\x01\n" +
	"\fGroupService\x12^\n" +
	"\x03Get\x12\x1e.proto.example.GetGroupRequest\x1a\x1f.proto.example.GetGroupResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/group/{id}\x12\\\n" +
	"\x04List\x12\x1f.proto.example.ListGroupRequest\x1a .proto.example.ListGroupResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/group2\xef\x06\n" +
	"\vUserService\x12|\n" +
	"\n" +
	"SetGroupId\x12$.proto.example.SetUserGroupIdRequest\x1a%.proto.example.SetUserGroupIdResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/v1/user/{id}/group_id\x12w\n" +
	"\tSetStatus\x12#.proto.example.SetUserStatusRequest\x1a$.proto.example.SetUserStatusResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/v1/user/{id}/status\x12~\n" +
	"\x0eListUserGroups\x12(.proto.example.ListUserUserGroupsRequest\x1a .proto.example.ListGroupResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/user/{id}/usergroups\x12[\n" +
	"\x03Get\x12\x1d.proto.example.GetUserRequest\x1a\x1e.proto.example.GetUserResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/user/{id}\x12Y\n" +
	"\x04List\x12\x1e.proto.example.ListUserRequest\x1a\x1f.proto.example.ListUserResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/user\x12b\n" +
	"\x06Create\x12 .proto.example.CreateUserRequest\x1a!.proto.example.CreateUserResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/user\x12g\n" +
	"\x06Update\x12 .proto.example.UpdateUserRequest\x1a!.proto.example.UpdateUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/v1/user/{id}\x12d\n" +
	"\x06Delete\x12 .proto.example.DeleteUserRequest\x1a!.proto.example.DeleteUserResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/v1/user/{id}B6Z4github.com/syralon/entc-gen-go/example/proto/exampleb\x06proto3"

var (
	file_proto_example_ent_service_proto_rawDescOnce sync.Once
	file_proto_example_ent_service_proto_rawDescData []byte
)

func file_proto_example_ent_service_proto_rawDescGZIP() []byte {
	file_proto_example_ent_service_proto_rawDescOnce.Do(func() {
		file_proto_example_ent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_example_ent_service_proto_rawDesc), len(file_proto_example_ent_service_proto_rawDesc)))
	})
	return file_proto_example_ent_service_proto_rawDescData
}

var file_proto_example_ent_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_example_ent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_example_ent_service_proto_goTypes = []any{
	(GroupOrder)(0),                   // 0: proto.example.GroupOrder
	(UserOrder)(0),                    // 1: proto.example.UserOrder
	(*GroupOptions)(nil),              // 2: proto.example.GroupOptions
	(*UserOptions)(nil),               // 3: proto.example.UserOptions
	(*GroupUpdate)(nil),               // 4: proto.example.GroupUpdate
	(*UserUpdate)(nil),                // 5: proto.example.UserUpdate
	(*ListGroupOrder)(nil),            // 6: proto.example.ListGroupOrder
	(*ListUserOrder)(nil),             // 7: proto.example.ListUserOrder
	(*GetGroupRequest)(nil),           // 8: proto.example.GetGroupRequest
	(*GetGroupResponse)(nil),          // 9: proto.example.GetGroupResponse
	(*GetUserRequest)(nil),            // 10: proto.example.GetUserRequest
	(*GetUserResponse)(nil),           // 11: proto.example.GetUserResponse
	(*ListGroupRequest)(nil),          // 12: proto.example.ListGroupRequest
	(*ListGroupResponse)(nil),         // 13: proto.example.ListGroupResponse
	(*ListUserRequest)(nil),           // 14: proto.example.ListUserRequest
	(*ListUserResponse)(nil),          // 15: proto.example.ListUserResponse
	(*CreateUserRequest)(nil),         // 16: proto.example.CreateUserRequest
	(*CreateUserResponse)(nil),        // 17: proto.example.CreateUserResponse
	(*UpdateUserRequest)(nil),         // 18: proto.example.UpdateUserRequest
	(*UpdateUserResponse)(nil),        // 19: proto.example.UpdateUserResponse
	(*DeleteUserRequest)(nil),         // 20: proto.example.DeleteUserRequest
	(*DeleteUserResponse)(nil),        // 21: proto.example.DeleteUserResponse
	(*SetUserGroupIdRequest)(nil),     // 22: proto.example.SetUserGroupIdRequest
	(*SetUserGroupIdResponse)(nil),    // 23: proto.example.SetUserGroupIdResponse
	(*SetUserStatusRequest)(nil),      // 24: proto.example.SetUserStatusRequest
	(*SetUserStatusResponse)(nil),     // 25: proto.example.SetUserStatusResponse
	(*ListUserUserGroupsRequest)(nil), // 26: proto.example.ListUserUserGroupsRequest
	(*entproto.Int64Field)(nil),       // 27: syralon.entproto.Int64Field
	(*entproto.StringField)(nil),      // 28: syralon.entproto.StringField
	(*entproto.TimestampField)(nil),   // 29: syralon.entproto.TimestampField
	(*entproto.Int32Field)(nil),       // 30: syralon.entproto.Int32Field
	(*Group)(nil),                     // 31: proto.example.Group
	(*User)(nil),                      // 32: proto.example.User
	(*entproto.Paginator)(nil),        // 33: syralon.entproto.Paginator
	(*timestamppb.Timestamp)(nil),     // 34: google.protobuf.Timestamp
}
var file_proto_example_ent_service_proto_depIdxs = []int32{
	27, // 0: proto.example.GroupOptions.id:type_name -> syralon.entproto.Int64Field
	28, // 1: proto.example.GroupOptions.name:type_name -> syralon.entproto.StringField
	29, // 2: proto.example.GroupOptions.created_at:type_name -> syralon.entproto.TimestampField
	29, // 3: proto.example.GroupOptions.updated_at:type_name -> syralon.entproto.TimestampField
	3,  // 4: proto.example.GroupOptions.group_users:type_name -> proto.example.UserOptions
	27, // 5: proto.example.UserOptions.id:type_name -> syralon.entproto.Int64Field
	28, // 6: proto.example.UserOptions.name:type_name -> syralon.entproto.StringField
	29, // 7: proto.example.UserOptions.created_at:type_name -> syralon.entproto.TimestampField
	29, // 8: proto.example.UserOptions.updated_at:type_name -> syralon.entproto.TimestampField
	27, // 9: proto.example.UserOptions.group_id:type_name -> syralon.entproto.Int64Field
	30, // 10: proto.example.UserOptions.status:type_name -> syralon.entproto.Int32Field
	2,  // 11: proto.example.UserOptions.user_groups:type_name -> proto.example.GroupOptions
	5,  // 12: proto.example.GroupUpdate.group_users:type_name -> proto.example.UserUpdate
	4,  // 13: proto.example.UserUpdate.user_groups:type_name -> proto.example.GroupUpdate
	0,  // 14: proto.example.ListGroupOrder.by:type_name -> proto.example.GroupOrder
	1,  // 15: proto.example.ListUserOrder.by:type_name -> proto.example.UserOrder
	31, // 16: proto.example.GetGroupResponse.data:type_name -> proto.example.Group
	32, // 17: proto.example.GetUserResponse.data:type_name -> proto.example.User
	2,  // 18: proto.example.ListGroupRequest.options:type_name -> proto.example.GroupOptions
	6,  // 19: proto.example.ListGroupRequest.orders:type_name -> proto.example.ListGroupOrder
	33, // 20: proto.example.ListGroupRequest.paginator:type_name -> syralon.entproto.Paginator
	31, // 21: proto.example.ListGroupResponse.data:type_name -> proto.example.Group
	3,  // 22: proto.example.ListUserRequest.options:type_name -> proto.example.UserOptions
	7,  // 23: proto.example.ListUserRequest.orders:type_name -> proto.example.ListUserOrder
	33, // 24: proto.example.ListUserRequest.paginator:type_name -> syralon.entproto.Paginator
	32, // 25: proto.example.ListUserResponse.data:type_name -> proto.example.User
	34, // 26: proto.example.CreateUserRequest.created_at:type_name -> google.protobuf.Timestamp
	34, // 27: proto.example.CreateUserRequest.updated_at:type_name -> google.protobuf.Timestamp
	31, // 28: proto.example.CreateUserRequest.user_groups:type_name -> proto.example.Group
	5,  // 29: proto.example.UpdateUserRequest.update:type_name -> proto.example.UserUpdate
	3,  // 30: proto.example.SetUserGroupIdRequest.options:type_name -> proto.example.UserOptions
	3,  // 31: proto.example.SetUserStatusRequest.options:type_name -> proto.example.UserOptions
	2,  // 32: proto.example.ListUserUserGroupsRequest.options:type_name -> proto.example.GroupOptions
	6,  // 33: proto.example.ListUserUserGroupsRequest.orders:type_name -> proto.example.ListGroupOrder
	33, // 34: proto.example.ListUserUserGroupsRequest.paginator:type_name -> syralon.entproto.Paginator
	8,  // 35: proto.example.GroupService.Get:input_type -> proto.example.GetGroupRequest
	12, // 36: proto.example.GroupService.List:input_type -> proto.example.ListGroupRequest
	22, // 37: proto.example.UserService.SetGroupId:input_type -> proto.example.SetUserGroupIdRequest
	24, // 38: proto.example.UserService.SetStatus:input_type -> proto.example.SetUserStatusRequest
	26, // 39: proto.example.UserService.ListUserGroups:input_type -> proto.example.ListUserUserGroupsRequest
	10, // 40: proto.example.UserService.Get:input_type -> proto.example.GetUserRequest
	14, // 41: proto.example.UserService.List:input_type -> proto.example.ListUserRequest
	16, // 42: proto.example.UserService.Create:input_type -> proto.example.CreateUserRequest
	18, // 43: proto.example.UserService.Update:input_type -> proto.example.UpdateUserRequest
	20, // 44: proto.example.UserService.Delete:input_type -> proto.example.DeleteUserRequest
	9,  // 45: proto.example.GroupService.Get:output_type -> proto.example.GetGroupResponse
	13, // 46: proto.example.GroupService.List:output_type -> proto.example.ListGroupResponse
	23, // 47: proto.example.UserService.SetGroupId:output_type -> proto.example.SetUserGroupIdResponse
	25, // 48: proto.example.UserService.SetStatus:output_type -> proto.example.SetUserStatusResponse
	13, // 49: proto.example.UserService.ListUserGroups:output_type -> proto.example.ListGroupResponse
	11, // 50: proto.example.UserService.Get:output_type -> proto.example.GetUserResponse
	15, // 51: proto.example.UserService.List:output_type -> proto.example.ListUserResponse
	17, // 52: proto.example.UserService.Create:output_type -> proto.example.CreateUserResponse
	19, // 53: proto.example.UserService.Update:output_type -> proto.example.UpdateUserResponse
	21, // 54: proto.example.UserService.Delete:output_type -> proto.example.DeleteUserResponse
	45, // [45:55] is the sub-list for method output_type
	35, // [35:45] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_proto_example_ent_service_proto_init() }
func file_proto_example_ent_service_proto_init() {
	if File_proto_example_ent_service_proto != nil {
		return
	}
	file_proto_example_ent_proto_init()
	file_proto_example_ent_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_example_ent_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_example_ent_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_example_ent_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_example_ent_service_proto_rawDesc), len(file_proto_example_ent_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_example_ent_service_proto_goTypes,
		DependencyIndexes: file_proto_example_ent_service_proto_depIdxs,
		EnumInfos:         file_proto_example_ent_service_proto_enumTypes,
		MessageInfos:      file_proto_example_ent_service_proto_msgTypes,
	}.Build()
	File_proto_example_ent_service_proto = out.File
	file_proto_example_ent_service_proto_goTypes = nil
	file_proto_example_ent_service_proto_depIdxs = nil
}
