// Code generated by protoc-gen-go-http. DO NOT EDIT.

package example

import (
	context "context"
	middleware "github.com/go-kratos/kratos/v2/middleware"
	http1 "github.com/go-kratos/kratos/v2/transport/http"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
// context./http./middleware.
const _ = http1.SupportPackageIsVersion1

type GroupServiceHTTPServer interface {
	Get(context.Context, *GetGroupRequest) (*GetGroupResponse, error)

	List(context.Context, *ListGroupRequest) (*ListGroupResponse, error)
}

func RegisterGroupServiceHTTPServer(s http1.ServiceRegistrar, srv GroupServiceHTTPServer) {
	s.RegisterService(&_HTTP_GroupService_serviceDesc, srv)
}

func _HTTP_GroupService_Get_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in GetGroupRequest

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).Get(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_GroupService_List_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in ListGroupRequest

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).List(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _HTTP_GroupService_serviceDesc = http1.ServiceDesc{
	ServiceName: "example.proto.example.GroupService",
	Methods: []http1.MethodDesc{

		{
			Path:    "/v1/group/{id}",
			Method:  "GET",
			Handler: _HTTP_GroupService_Get_0,
		},

		{
			Path:    "/v1/group",
			Method:  "GET",
			Handler: _HTTP_GroupService_List_0,
		},
	},
	Metadata: "proto/example/ent_service.proto",
}

type UserServiceHTTPServer interface {
	Create(context.Context, *CreateUserRequest) (*CreateUserResponse, error)

	Delete(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)

	Get(context.Context, *GetUserRequest) (*GetUserResponse, error)

	List(context.Context, *ListUserRequest) (*ListUserResponse, error)

	ListUserGroups(context.Context, *ListUserUserGroupsRequest) (*ListGroupResponse, error)

	SetGroupId(context.Context, *SetUserGroupIdRequest) (*SetUserGroupIdResponse, error)

	SetStatus(context.Context, *SetUserStatusRequest) (*SetUserStatusResponse, error)

	Update(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
}

func RegisterUserServiceHTTPServer(s http1.ServiceRegistrar, srv UserServiceHTTPServer) {
	s.RegisterService(&_HTTP_UserService_serviceDesc, srv)
}

func _HTTP_UserService_SetGroupId_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in SetUserGroupIdRequest

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	if err := dec(&in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetGroupId(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_UserService_SetStatus_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in SetUserStatusRequest

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	if err := dec(&in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetStatus(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_UserService_ListUserGroups_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in ListUserUserGroupsRequest

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUserGroups(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_UserService_Get_1(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in GetUserRequest

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_UserService_List_1(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in ListUserRequest

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).List(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_UserService_Create_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in CreateUserRequest

	if err := dec(&in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_UserService_Update_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in UpdateUserRequest

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	if err := dec(&in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_UserService_Delete_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in DeleteUserRequest

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _HTTP_UserService_serviceDesc = http1.ServiceDesc{
	ServiceName: "example.proto.example.UserService",
	Methods: []http1.MethodDesc{

		{
			Path:    "/v1/user/{id}/group_id",
			Method:  "PUT",
			Handler: _HTTP_UserService_SetGroupId_0,
		},

		{
			Path:    "/v1/user/{id}/status",
			Method:  "PUT",
			Handler: _HTTP_UserService_SetStatus_0,
		},

		{
			Path:    "/v1/user/{id}/usergroups",
			Method:  "GET",
			Handler: _HTTP_UserService_ListUserGroups_0,
		},

		{
			Path:    "/v1/user/{id}",
			Method:  "GET",
			Handler: _HTTP_UserService_Get_1,
		},

		{
			Path:    "/v1/user",
			Method:  "GET",
			Handler: _HTTP_UserService_List_1,
		},

		{
			Path:    "/v1/user",
			Method:  "POST",
			Handler: _HTTP_UserService_Create_0,
		},

		{
			Path:    "/v1/user/{id}",
			Method:  "PUT",
			Handler: _HTTP_UserService_Update_0,
		},

		{
			Path:    "/v1/user/{id}",
			Method:  "DELETE",
			Handler: _HTTP_UserService_Delete_0,
		},
	},
	Metadata: "proto/example/ent_service.proto",
}
