// Code generated by chocoproto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/example/ent_service.proto

package example

import (
	_ "github.com/google/gnostic/openapiv3"
	entproto "github.com/syralon/entc-gen-go/proto/syralon/entproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupOrder int32

const (
	GroupOrder_GROUP_ORDER_BY_ID         GroupOrder = 0
	GroupOrder_GROUP_ORDER_BY_CREATED_AT GroupOrder = 1
	GroupOrder_GROUP_ORDER_BY_UPDATED_AT GroupOrder = 2
)

// Enum value maps for GroupOrder.
var (
	GroupOrder_name = map[int32]string{
		0: "GROUP_ORDER_BY_ID",
		1: "GROUP_ORDER_BY_CREATED_AT",
		2: "GROUP_ORDER_BY_UPDATED_AT",
	}
	GroupOrder_value = map[string]int32{
		"GROUP_ORDER_BY_ID":         0,
		"GROUP_ORDER_BY_CREATED_AT": 1,
		"GROUP_ORDER_BY_UPDATED_AT": 2,
	}
)

func (x GroupOrder) Enum() *GroupOrder {
	p := new(GroupOrder)
	*p = x
	return p
}

func (x GroupOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_example_ent_service_proto_enumTypes[0].Descriptor()
}

func (GroupOrder) Type() protoreflect.EnumType {
	return &file_proto_example_ent_service_proto_enumTypes[0]
}

func (x GroupOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupOrder.Descriptor instead.
func (GroupOrder) EnumDescriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{0}
}

type UserOrder int32

const (
	UserOrder_USER_ORDER_BY_ID         UserOrder = 0
	UserOrder_USER_ORDER_BY_CREATED_AT UserOrder = 1
	UserOrder_USER_ORDER_BY_GROUP_ID   UserOrder = 2
)

// Enum value maps for UserOrder.
var (
	UserOrder_name = map[int32]string{
		0: "USER_ORDER_BY_ID",
		1: "USER_ORDER_BY_CREATED_AT",
		2: "USER_ORDER_BY_GROUP_ID",
	}
	UserOrder_value = map[string]int32{
		"USER_ORDER_BY_ID":         0,
		"USER_ORDER_BY_CREATED_AT": 1,
		"USER_ORDER_BY_GROUP_ID":   2,
	}
)

func (x UserOrder) Enum() *UserOrder {
	p := new(UserOrder)
	*p = x
	return p
}

func (x UserOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_example_ent_service_proto_enumTypes[1].Descriptor()
}

func (UserOrder) Type() protoreflect.EnumType {
	return &file_proto_example_ent_service_proto_enumTypes[1]
}

func (x UserOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserOrder.Descriptor instead.
func (UserOrder) EnumDescriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{1}
}

type GroupOptions struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            *entproto.Int64Field     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *entproto.StringField    `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	CreatedAt     *entproto.TimestampField `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt     *entproto.TimestampField `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	GroupUsers    *UserOptions             `protobuf:"bytes,5,opt,name=group_users,json=groupUsers,proto3" json:"group_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupOptions) Reset() {
	*x = GroupOptions{}
	mi := &file_proto_example_ent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupOptions) ProtoMessage() {}

func (x *GroupOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupOptions.ProtoReflect.Descriptor instead.
func (*GroupOptions) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{0}
}

func (x *GroupOptions) GetId() *entproto.Int64Field {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GroupOptions) GetName() *entproto.StringField {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *GroupOptions) GetCreatedAt() *entproto.TimestampField {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GroupOptions) GetUpdatedAt() *entproto.TimestampField {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GroupOptions) GetGroupUsers() *UserOptions {
	if x != nil {
		return x.GroupUsers
	}
	return nil
}

type UserOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *entproto.Int64Field   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The user name
	Name *entproto.StringField `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// The created time
	CreatedAt *entproto.TimestampField `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	// The latest update time
	UpdatedAt     *entproto.TimestampField `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	GroupId       *entproto.Int64Field     `protobuf:"bytes,5,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Status        *entproto.Int32Field     `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	UserGroups    *GroupOptions            `protobuf:"bytes,7,opt,name=user_groups,json=userGroups,proto3" json:"user_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOptions) Reset() {
	*x = UserOptions{}
	mi := &file_proto_example_ent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOptions) ProtoMessage() {}

func (x *UserOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOptions.ProtoReflect.Descriptor instead.
func (*UserOptions) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserOptions) GetId() *entproto.Int64Field {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UserOptions) GetName() *entproto.StringField {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UserOptions) GetCreatedAt() *entproto.TimestampField {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserOptions) GetUpdatedAt() *entproto.TimestampField {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserOptions) GetGroupId() *entproto.Int64Field {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *UserOptions) GetStatus() *entproto.Int32Field {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UserOptions) GetUserGroups() *GroupOptions {
	if x != nil {
		return x.UserGroups
	}
	return nil
}

type GroupUpdateOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *entproto.Int64Field   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *entproto.StringField  `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	GroupUsers    *UserUpdateOptions     `protobuf:"bytes,3,opt,name=group_users,json=groupUsers,proto3" json:"group_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUpdateOptions) Reset() {
	*x = GroupUpdateOptions{}
	mi := &file_proto_example_ent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUpdateOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUpdateOptions) ProtoMessage() {}

func (x *GroupUpdateOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUpdateOptions.ProtoReflect.Descriptor instead.
func (*GroupUpdateOptions) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{2}
}

func (x *GroupUpdateOptions) GetId() *entproto.Int64Field {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GroupUpdateOptions) GetName() *entproto.StringField {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *GroupUpdateOptions) GetGroupUsers() *UserUpdateOptions {
	if x != nil {
		return x.GroupUsers
	}
	return nil
}

type UserUpdateOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *entproto.Int64Field   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The user name
	Name          *entproto.StringField `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	GroupId       *entproto.Int64Field  `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Status        *entproto.Int32Field  `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	UserGroups    *GroupUpdateOptions   `protobuf:"bytes,5,opt,name=user_groups,json=userGroups,proto3" json:"user_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateOptions) Reset() {
	*x = UserUpdateOptions{}
	mi := &file_proto_example_ent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateOptions) ProtoMessage() {}

func (x *UserUpdateOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateOptions.ProtoReflect.Descriptor instead.
func (*UserUpdateOptions) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{3}
}

func (x *UserUpdateOptions) GetId() *entproto.Int64Field {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UserUpdateOptions) GetName() *entproto.StringField {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UserUpdateOptions) GetGroupId() *entproto.Int64Field {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *UserUpdateOptions) GetStatus() *entproto.Int32Field {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UserUpdateOptions) GetUserGroups() *GroupUpdateOptions {
	if x != nil {
		return x.UserGroups
	}
	return nil
}

type ListGroupOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	By            GroupOrder             `protobuf:"varint,1,opt,name=by,proto3,enum=example.proto.example.GroupOrder" json:"by,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupOrder) Reset() {
	*x = ListGroupOrder{}
	mi := &file_proto_example_ent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupOrder) ProtoMessage() {}

func (x *ListGroupOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupOrder.ProtoReflect.Descriptor instead.
func (*ListGroupOrder) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListGroupOrder) GetBy() GroupOrder {
	if x != nil {
		return x.By
	}
	return GroupOrder_GROUP_ORDER_BY_ID
}

func (x *ListGroupOrder) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type ListUserOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	By            UserOrder              `protobuf:"varint,1,opt,name=by,proto3,enum=example.proto.example.UserOrder" json:"by,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserOrder) Reset() {
	*x = ListUserOrder{}
	mi := &file_proto_example_ent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOrder) ProtoMessage() {}

func (x *ListUserOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOrder.ProtoReflect.Descriptor instead.
func (*ListUserOrder) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserOrder) GetBy() UserOrder {
	if x != nil {
		return x.By
	}
	return UserOrder_USER_ORDER_BY_ID
}

func (x *ListUserOrder) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Group                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetGroupResponse) GetData() *Group {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *User                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *GroupOptions          `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Orders        []*ListGroupOrder      `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	Paginator     *entproto.Paginator    `protobuf:"bytes,3,opt,name=paginator,proto3" json:"paginator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupRequest) Reset() {
	*x = ListGroupRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupRequest) ProtoMessage() {}

func (x *ListGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupRequest.ProtoReflect.Descriptor instead.
func (*ListGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListGroupRequest) GetOptions() *GroupOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListGroupRequest) GetOrders() []*ListGroupOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListGroupRequest) GetPaginator() *entproto.Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

type ListGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Group               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupResponse) Reset() {
	*x = ListGroupResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupResponse) ProtoMessage() {}

func (x *ListGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupResponse.ProtoReflect.Descriptor instead.
func (*ListGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListGroupResponse) GetData() []*Group {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *UserOptions           `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Orders        []*ListUserOrder       `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	Paginator     *entproto.Paginator    `protobuf:"bytes,3,opt,name=paginator,proto3" json:"paginator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRequest) Reset() {
	*x = ListUserRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRequest) ProtoMessage() {}

func (x *ListUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRequest.ProtoReflect.Descriptor instead.
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserRequest) GetOptions() *UserOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListUserRequest) GetOrders() []*ListUserOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListUserRequest) GetPaginator() *entproto.Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

type ListUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*User                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserResponse) Reset() {
	*x = ListUserResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserResponse) ProtoMessage() {}

func (x *ListUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserResponse.ProtoReflect.Descriptor instead.
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListUserResponse) GetData() []*User {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	GroupUsers    []*User                `protobuf:"bytes,5,rep,name=group_users,json=groupUsers,proto3" json:"group_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{14}
}

func (x *CreateGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CreateGroupRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CreateGroupRequest) GetGroupUsers() []*User {
	if x != nil {
		return x.GroupUsers
	}
	return nil
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateGroupResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The user name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The created time
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The latest update time
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	GroupId       int64                  `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	UserGroups    []*Group               `protobuf:"bytes,7,rep,name=user_groups,json=userGroups,proto3" json:"user_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CreateUserRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CreateUserRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateUserRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateUserRequest) GetUserGroups() []*Group {
	if x != nil {
		return x.UserGroups
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{17}
}

func (x *CreateUserResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Options       *GroupUpdateOptions    `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGroupRequest) GetOptions() *GroupUpdateOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type UpdateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupResponse) Reset() {
	*x = UpdateGroupResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupResponse) ProtoMessage() {}

func (x *UpdateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{19}
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Options       *UserUpdateOptions     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetOptions() *UserUpdateOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{21}
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{23}
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{25}
}

type SetUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Options       *UserOptions           `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Set           int32                  `protobuf:"varint,3,opt,name=set,proto3" json:"set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserStatusRequest) Reset() {
	*x = SetUserStatusRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserStatusRequest) ProtoMessage() {}

func (x *SetUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserStatusRequest.ProtoReflect.Descriptor instead.
func (*SetUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{26}
}

func (x *SetUserStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetUserStatusRequest) GetOptions() *UserOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SetUserStatusRequest) GetSet() int32 {
	if x != nil {
		return x.Set
	}
	return 0
}

type SetUserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          int32                  `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserStatusResponse) Reset() {
	*x = SetUserStatusResponse{}
	mi := &file_proto_example_ent_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserStatusResponse) ProtoMessage() {}

func (x *SetUserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserStatusResponse.ProtoReflect.Descriptor instead.
func (*SetUserStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{27}
}

func (x *SetUserStatusResponse) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ListGroupGroupUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Options       *UserOptions           `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Orders        []*ListUserOrder       `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	Paginator     *entproto.Paginator    `protobuf:"bytes,4,opt,name=paginator,proto3" json:"paginator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupGroupUsersRequest) Reset() {
	*x = ListGroupGroupUsersRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupGroupUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupGroupUsersRequest) ProtoMessage() {}

func (x *ListGroupGroupUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupGroupUsersRequest.ProtoReflect.Descriptor instead.
func (*ListGroupGroupUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{28}
}

func (x *ListGroupGroupUsersRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListGroupGroupUsersRequest) GetOptions() *UserOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListGroupGroupUsersRequest) GetOrders() []*ListUserOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListGroupGroupUsersRequest) GetPaginator() *entproto.Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

type ListUserUserGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Options       *GroupOptions          `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Orders        []*ListGroupOrder      `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	Paginator     *entproto.Paginator    `protobuf:"bytes,4,opt,name=paginator,proto3" json:"paginator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserUserGroupsRequest) Reset() {
	*x = ListUserUserGroupsRequest{}
	mi := &file_proto_example_ent_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserUserGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserUserGroupsRequest) ProtoMessage() {}

func (x *ListUserUserGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_ent_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserUserGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListUserUserGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_ent_service_proto_rawDescGZIP(), []int{29}
}

func (x *ListUserUserGroupsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserUserGroupsRequest) GetOptions() *GroupOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListUserUserGroupsRequest) GetOrders() []*ListGroupOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListUserUserGroupsRequest) GetPaginator() *entproto.Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

var File_proto_example_ent_service_proto protoreflect.FileDescriptor

const file_proto_example_ent_service_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/example/ent_service.proto\x12\x15example.proto.example\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bopenapiv3/annotations.proto\x1a\x17proto/example/ent.proto\x1a\x1csyralon/entproto/field.proto\x1a syralon/entproto/paginator.proto\"\xec\x02\n" +
	"\fGroupOptions\x12,\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.syralon.entproto.Int64FieldR\x02id\x126\n" +
	"\x04name\x18\x02 \x01(\v2\x1d.syralon.entproto.StringFieldH\x00R\x04name\x88\x01\x01\x12D\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2 .syralon.entproto.TimestampFieldH\x01R\tcreatedAt\x88\x01\x01\x12D\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2 .syralon.entproto.TimestampFieldH\x02R\tupdatedAt\x88\x01\x01\x12C\n" +
	"\vgroup_users\x18\x05 \x01(\v2\".example.proto.example.UserOptionsR\n" +
	"groupUsersB\a\n" +
	"\x05_nameB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_at\"\x8d\x04\n" +
	"\vUserOptions\x12,\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.syralon.entproto.Int64FieldR\x02id\x12F\n" +
	"\x04name\x18\x02 \x01(\v2\x1d.syralon.entproto.StringFieldB\x0e\xbaG\v\x92\x02\bThe nameH\x00R\x04name\x88\x01\x01\x12D\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2 .syralon.entproto.TimestampFieldH\x01R\tcreatedAt\x88\x01\x01\x12D\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2 .syralon.entproto.TimestampFieldH\x02R\tupdatedAt\x88\x01\x01\x12<\n" +
	"\bgroup_id\x18\x05 \x01(\v2\x1c.syralon.entproto.Int64FieldH\x03R\agroupId\x88\x01\x01\x129\n" +
	"\x06status\x18\x06 \x01(\v2\x1c.syralon.entproto.Int32FieldH\x04R\x06status\x88\x01\x01\x12D\n" +
	"\vuser_groups\x18\a \x01(\v2#.example.proto.example.GroupOptionsR\n" +
	"userGroupsB\a\n" +
	"\x05_nameB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_atB\v\n" +
	"\t_group_idB\t\n" +
	"\a_status\"\xce\x01\n" +
	"\x12GroupUpdateOptions\x12,\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.syralon.entproto.Int64FieldR\x02id\x126\n" +
	"\x04name\x18\x02 \x01(\v2\x1d.syralon.entproto.StringFieldH\x00R\x04name\x88\x01\x01\x12I\n" +
	"\vgroup_users\x18\x03 \x01(\v2(.example.proto.example.UserUpdateOptionsR\n" +
	"groupUsersB\a\n" +
	"\x05_name\"\xef\x02\n" +
	"\x11UserUpdateOptions\x12,\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.syralon.entproto.Int64FieldR\x02id\x12F\n" +
	"\x04name\x18\x02 \x01(\v2\x1d.syralon.entproto.StringFieldB\x0e\xbaG\v\x92\x02\bThe nameH\x00R\x04name\x88\x01\x01\x12<\n" +
	"\bgroup_id\x18\x03 \x01(\v2\x1c.syralon.entproto.Int64FieldH\x01R\agroupId\x88\x01\x01\x129\n" +
	"\x06status\x18\x04 \x01(\v2\x1c.syralon.entproto.Int32FieldH\x02R\x06status\x88\x01\x01\x12J\n" +
	"\vuser_groups\x18\x05 \x01(\v2).example.proto.example.GroupUpdateOptionsR\n" +
	"userGroupsB\a\n" +
	"\x05_nameB\v\n" +
	"\t_group_idB\t\n" +
	"\a_status\"W\n" +
	"\x0eListGroupOrder\x121\n" +
	"\x02by\x18\x01 \x01(\x0e2!.example.proto.example.GroupOrderR\x02by\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"U\n" +
	"\rListUserOrder\x120\n" +
	"\x02by\x18\x01 \x01(\x0e2 .example.proto.example.UserOrderR\x02by\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"!\n" +
	"\x0fGetGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"D\n" +
	"\x10GetGroupResponse\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.example.proto.example.GroupR\x04data\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"B\n" +
	"\x0fGetUserResponse\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.example.proto.example.UserR\x04data\"\xcb\x01\n" +
	"\x10ListGroupRequest\x12=\n" +
	"\aoptions\x18\x01 \x01(\v2#.example.proto.example.GroupOptionsR\aoptions\x12=\n" +
	"\x06orders\x18\x02 \x03(\v2%.example.proto.example.ListGroupOrderR\x06orders\x129\n" +
	"\tpaginator\x18\x03 \x01(\v2\x1b.syralon.entproto.PaginatorR\tpaginator\"E\n" +
	"\x11ListGroupResponse\x120\n" +
	"\x04data\x18\x01 \x03(\v2\x1c.example.proto.example.GroupR\x04data\"\xc8\x01\n" +
	"\x0fListUserRequest\x12<\n" +
	"\aoptions\x18\x01 \x01(\v2\".example.proto.example.UserOptionsR\aoptions\x12<\n" +
	"\x06orders\x18\x02 \x03(\v2$.example.proto.example.ListUserOrderR\x06orders\x129\n" +
	"\tpaginator\x18\x03 \x01(\v2\x1b.syralon.entproto.PaginatorR\tpaginator\"C\n" +
	"\x10ListUserResponse\x12/\n" +
	"\x04data\x18\x01 \x03(\v2\x1b.example.proto.example.UserR\x04data\"\xec\x01\n" +
	"\x12CreateGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12<\n" +
	"\vgroup_users\x18\x05 \x03(\v2\x1b.example.proto.example.UserR\n" +
	"groupUsers\"%\n" +
	"\x13CreateGroupResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xaf\x02\n" +
	"\x11CreateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\x04name\x18\x02 \x01(\tB\x0e\xbaG\v\x92\x02\bThe nameR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12=\n" +
	"\vuser_groups\x18\a \x03(\v2\x1c.example.proto.example.GroupR\n" +
	"userGroups\"$\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"i\n" +
	"\x12UpdateGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12C\n" +
	"\aoptions\x18\x02 \x01(\v2).example.proto.example.GroupUpdateOptionsR\aoptions\"\x15\n" +
	"\x13UpdateGroupResponse\"g\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12B\n" +
	"\aoptions\x18\x02 \x01(\v2(.example.proto.example.UserUpdateOptionsR\aoptions\"\x14\n" +
	"\x12UpdateUserResponse\"$\n" +
	"\x12DeleteGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x15\n" +
	"\x13DeleteGroupResponse\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteUserResponse\"\x7f\n" +
	"\x14SetUserStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12<\n" +
	"\aoptions\x18\x02 \x01(\v2\".example.proto.example.UserOptionsR\aoptions\x12\x10\n" +
	"\x03set\x18\x03 \x01(\x05R\x03set\"+\n" +
	"\x15SetUserStatusResponse\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x05R\x04rows\"\xee\x01\n" +
	"\x1aListGroupGroupUsersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12<\n" +
	"\aoptions\x18\x02 \x01(\v2\".example.proto.example.UserOptionsR\aoptions\x12<\n" +
	"\x06orders\x18\x03 \x03(\v2$.example.proto.example.ListUserOrderR\x06orders\x129\n" +
	"\tpaginator\x18\x04 \x01(\v2\x1b.syralon.entproto.PaginatorR\tpaginator\"\xed\x01\n" +
	"\x19ListUserUserGroupsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12=\n" +
	"\aoptions\x18\x02 \x01(\v2#.example.proto.example.GroupOptionsR\aoptions\x12=\n" +
	"\x06orders\x18\x03 \x03(\v2%.example.proto.example.ListGroupOrderR\x06orders\x129\n" +
	"\tpaginator\x18\x04 \x01(\v2\x1b.syralon.entproto.PaginatorR\tpaginator*a\n" +
	"\n" +
	"GroupOrder\x12\x15\n" +
	"\x11GROUP_ORDER_BY_ID\x10\x00\x12\x1d\n" +
	"\x19GROUP_ORDER_BY_CREATED_AT\x10\x01\x12\x1d\n" +
	"\x19GROUP_ORDER_BY_UPDATED_AT\x10\x02*[\n" +
	"\tUserOrder\x12\x14\n" +
	"\x10USER_ORDER_BY_ID\x10\x00\x12\x1c\n" +
	"\x18USER_ORDER_BY_CREATED_AT\x10\x01\x12\x1a\n" +
	"\x16USER_ORDER_BY_GROUP_ID\x10\x022\xf0\x05\n" +
	"\fGroupService\x12\x95\x01\n" +
	"\x0eListGroupUsers\x121.example.proto.example.ListGroupGroupUsersRequest\x1a'.example.proto.example.ListUserResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/group/{group_id}/groupusers\x12n\n" +
	"\x03Get\x12&.example.proto.example.GetGroupRequest\x1a'.example.proto.example.GetGroupResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/group/{id}\x12l\n" +
	"\x04List\x12'.example.proto.example.ListGroupRequest\x1a(.example.proto.example.ListGroupResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/group\x12u\n" +
	"\x06Create\x12).example.proto.example.CreateGroupRequest\x1a*.example.proto.example.CreateGroupResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/group\x12z\n" +
	"\x06Update\x12).example.proto.example.UpdateGroupRequest\x1a*.example.proto.example.UpdateGroupResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/group/{id}\x12w\n" +
	"\x06Delete\x12).example.proto.example.DeleteGroupRequest\x1a*.example.proto.example.DeleteGroupResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/group/{id}2\xed\x06\n" +
	"\vUserService\x12\x8c\x01\n" +
	"\tSetStatus\x12+.example.proto.example.SetUserStatusRequest\x1a,.example.proto.example.SetUserStatusResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/v1/user/{user_id}/status\x12\x93\x01\n" +
	"\x0eListUserGroups\x120.example.proto.example.ListUserUserGroupsRequest\x1a(.example.proto.example.ListGroupResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/user/{user_id}/usergroups\x12k\n" +
	"\x03Get\x12%.example.proto.example.GetUserRequest\x1a&.example.proto.example.GetUserResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/user/{id}\x12i\n" +
	"\x04List\x12&.example.proto.example.ListUserRequest\x1a'.example.proto.example.ListUserResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/user\x12r\n" +
	"\x06Create\x12(.example.proto.example.CreateUserRequest\x1a).example.proto.example.CreateUserResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/user\x12w\n" +
	"\x06Update\x12(.example.proto.example.UpdateUserRequest\x1a).example.proto.example.UpdateUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/user/{id}\x12t\n" +
	"\x06Delete\x12(.example.proto.example.DeleteUserRequest\x1a).example.proto.example.DeleteUserResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/v1/user/{id}B>Z<github.com/syralon/entc-gen-go/example/proto/example;exampleb\x06proto3"

var (
	file_proto_example_ent_service_proto_rawDescOnce sync.Once
	file_proto_example_ent_service_proto_rawDescData []byte
)

func file_proto_example_ent_service_proto_rawDescGZIP() []byte {
	file_proto_example_ent_service_proto_rawDescOnce.Do(func() {
		file_proto_example_ent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_example_ent_service_proto_rawDesc), len(file_proto_example_ent_service_proto_rawDesc)))
	})
	return file_proto_example_ent_service_proto_rawDescData
}

var file_proto_example_ent_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_example_ent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_example_ent_service_proto_goTypes = []any{
	(GroupOrder)(0),                    // 0: example.proto.example.GroupOrder
	(UserOrder)(0),                     // 1: example.proto.example.UserOrder
	(*GroupOptions)(nil),               // 2: example.proto.example.GroupOptions
	(*UserOptions)(nil),                // 3: example.proto.example.UserOptions
	(*GroupUpdateOptions)(nil),         // 4: example.proto.example.GroupUpdateOptions
	(*UserUpdateOptions)(nil),          // 5: example.proto.example.UserUpdateOptions
	(*ListGroupOrder)(nil),             // 6: example.proto.example.ListGroupOrder
	(*ListUserOrder)(nil),              // 7: example.proto.example.ListUserOrder
	(*GetGroupRequest)(nil),            // 8: example.proto.example.GetGroupRequest
	(*GetGroupResponse)(nil),           // 9: example.proto.example.GetGroupResponse
	(*GetUserRequest)(nil),             // 10: example.proto.example.GetUserRequest
	(*GetUserResponse)(nil),            // 11: example.proto.example.GetUserResponse
	(*ListGroupRequest)(nil),           // 12: example.proto.example.ListGroupRequest
	(*ListGroupResponse)(nil),          // 13: example.proto.example.ListGroupResponse
	(*ListUserRequest)(nil),            // 14: example.proto.example.ListUserRequest
	(*ListUserResponse)(nil),           // 15: example.proto.example.ListUserResponse
	(*CreateGroupRequest)(nil),         // 16: example.proto.example.CreateGroupRequest
	(*CreateGroupResponse)(nil),        // 17: example.proto.example.CreateGroupResponse
	(*CreateUserRequest)(nil),          // 18: example.proto.example.CreateUserRequest
	(*CreateUserResponse)(nil),         // 19: example.proto.example.CreateUserResponse
	(*UpdateGroupRequest)(nil),         // 20: example.proto.example.UpdateGroupRequest
	(*UpdateGroupResponse)(nil),        // 21: example.proto.example.UpdateGroupResponse
	(*UpdateUserRequest)(nil),          // 22: example.proto.example.UpdateUserRequest
	(*UpdateUserResponse)(nil),         // 23: example.proto.example.UpdateUserResponse
	(*DeleteGroupRequest)(nil),         // 24: example.proto.example.DeleteGroupRequest
	(*DeleteGroupResponse)(nil),        // 25: example.proto.example.DeleteGroupResponse
	(*DeleteUserRequest)(nil),          // 26: example.proto.example.DeleteUserRequest
	(*DeleteUserResponse)(nil),         // 27: example.proto.example.DeleteUserResponse
	(*SetUserStatusRequest)(nil),       // 28: example.proto.example.SetUserStatusRequest
	(*SetUserStatusResponse)(nil),      // 29: example.proto.example.SetUserStatusResponse
	(*ListGroupGroupUsersRequest)(nil), // 30: example.proto.example.ListGroupGroupUsersRequest
	(*ListUserUserGroupsRequest)(nil),  // 31: example.proto.example.ListUserUserGroupsRequest
	(*entproto.Int64Field)(nil),        // 32: syralon.entproto.Int64Field
	(*entproto.StringField)(nil),       // 33: syralon.entproto.StringField
	(*entproto.TimestampField)(nil),    // 34: syralon.entproto.TimestampField
	(*entproto.Int32Field)(nil),        // 35: syralon.entproto.Int32Field
	(*Group)(nil),                      // 36: example.proto.example.Group
	(*User)(nil),                       // 37: example.proto.example.User
	(*entproto.Paginator)(nil),         // 38: syralon.entproto.Paginator
	(*timestamppb.Timestamp)(nil),      // 39: google.protobuf.Timestamp
}
var file_proto_example_ent_service_proto_depIdxs = []int32{
	32, // 0: example.proto.example.GroupOptions.id:type_name -> syralon.entproto.Int64Field
	33, // 1: example.proto.example.GroupOptions.name:type_name -> syralon.entproto.StringField
	34, // 2: example.proto.example.GroupOptions.created_at:type_name -> syralon.entproto.TimestampField
	34, // 3: example.proto.example.GroupOptions.updated_at:type_name -> syralon.entproto.TimestampField
	3,  // 4: example.proto.example.GroupOptions.group_users:type_name -> example.proto.example.UserOptions
	32, // 5: example.proto.example.UserOptions.id:type_name -> syralon.entproto.Int64Field
	33, // 6: example.proto.example.UserOptions.name:type_name -> syralon.entproto.StringField
	34, // 7: example.proto.example.UserOptions.created_at:type_name -> syralon.entproto.TimestampField
	34, // 8: example.proto.example.UserOptions.updated_at:type_name -> syralon.entproto.TimestampField
	32, // 9: example.proto.example.UserOptions.group_id:type_name -> syralon.entproto.Int64Field
	35, // 10: example.proto.example.UserOptions.status:type_name -> syralon.entproto.Int32Field
	2,  // 11: example.proto.example.UserOptions.user_groups:type_name -> example.proto.example.GroupOptions
	32, // 12: example.proto.example.GroupUpdateOptions.id:type_name -> syralon.entproto.Int64Field
	33, // 13: example.proto.example.GroupUpdateOptions.name:type_name -> syralon.entproto.StringField
	5,  // 14: example.proto.example.GroupUpdateOptions.group_users:type_name -> example.proto.example.UserUpdateOptions
	32, // 15: example.proto.example.UserUpdateOptions.id:type_name -> syralon.entproto.Int64Field
	33, // 16: example.proto.example.UserUpdateOptions.name:type_name -> syralon.entproto.StringField
	32, // 17: example.proto.example.UserUpdateOptions.group_id:type_name -> syralon.entproto.Int64Field
	35, // 18: example.proto.example.UserUpdateOptions.status:type_name -> syralon.entproto.Int32Field
	4,  // 19: example.proto.example.UserUpdateOptions.user_groups:type_name -> example.proto.example.GroupUpdateOptions
	0,  // 20: example.proto.example.ListGroupOrder.by:type_name -> example.proto.example.GroupOrder
	1,  // 21: example.proto.example.ListUserOrder.by:type_name -> example.proto.example.UserOrder
	36, // 22: example.proto.example.GetGroupResponse.data:type_name -> example.proto.example.Group
	37, // 23: example.proto.example.GetUserResponse.data:type_name -> example.proto.example.User
	2,  // 24: example.proto.example.ListGroupRequest.options:type_name -> example.proto.example.GroupOptions
	6,  // 25: example.proto.example.ListGroupRequest.orders:type_name -> example.proto.example.ListGroupOrder
	38, // 26: example.proto.example.ListGroupRequest.paginator:type_name -> syralon.entproto.Paginator
	36, // 27: example.proto.example.ListGroupResponse.data:type_name -> example.proto.example.Group
	3,  // 28: example.proto.example.ListUserRequest.options:type_name -> example.proto.example.UserOptions
	7,  // 29: example.proto.example.ListUserRequest.orders:type_name -> example.proto.example.ListUserOrder
	38, // 30: example.proto.example.ListUserRequest.paginator:type_name -> syralon.entproto.Paginator
	37, // 31: example.proto.example.ListUserResponse.data:type_name -> example.proto.example.User
	39, // 32: example.proto.example.CreateGroupRequest.created_at:type_name -> google.protobuf.Timestamp
	39, // 33: example.proto.example.CreateGroupRequest.updated_at:type_name -> google.protobuf.Timestamp
	37, // 34: example.proto.example.CreateGroupRequest.group_users:type_name -> example.proto.example.User
	39, // 35: example.proto.example.CreateUserRequest.created_at:type_name -> google.protobuf.Timestamp
	39, // 36: example.proto.example.CreateUserRequest.updated_at:type_name -> google.protobuf.Timestamp
	36, // 37: example.proto.example.CreateUserRequest.user_groups:type_name -> example.proto.example.Group
	4,  // 38: example.proto.example.UpdateGroupRequest.options:type_name -> example.proto.example.GroupUpdateOptions
	5,  // 39: example.proto.example.UpdateUserRequest.options:type_name -> example.proto.example.UserUpdateOptions
	3,  // 40: example.proto.example.SetUserStatusRequest.options:type_name -> example.proto.example.UserOptions
	3,  // 41: example.proto.example.ListGroupGroupUsersRequest.options:type_name -> example.proto.example.UserOptions
	7,  // 42: example.proto.example.ListGroupGroupUsersRequest.orders:type_name -> example.proto.example.ListUserOrder
	38, // 43: example.proto.example.ListGroupGroupUsersRequest.paginator:type_name -> syralon.entproto.Paginator
	2,  // 44: example.proto.example.ListUserUserGroupsRequest.options:type_name -> example.proto.example.GroupOptions
	6,  // 45: example.proto.example.ListUserUserGroupsRequest.orders:type_name -> example.proto.example.ListGroupOrder
	38, // 46: example.proto.example.ListUserUserGroupsRequest.paginator:type_name -> syralon.entproto.Paginator
	30, // 47: example.proto.example.GroupService.ListGroupUsers:input_type -> example.proto.example.ListGroupGroupUsersRequest
	8,  // 48: example.proto.example.GroupService.Get:input_type -> example.proto.example.GetGroupRequest
	12, // 49: example.proto.example.GroupService.List:input_type -> example.proto.example.ListGroupRequest
	16, // 50: example.proto.example.GroupService.Create:input_type -> example.proto.example.CreateGroupRequest
	20, // 51: example.proto.example.GroupService.Update:input_type -> example.proto.example.UpdateGroupRequest
	24, // 52: example.proto.example.GroupService.Delete:input_type -> example.proto.example.DeleteGroupRequest
	28, // 53: example.proto.example.UserService.SetStatus:input_type -> example.proto.example.SetUserStatusRequest
	31, // 54: example.proto.example.UserService.ListUserGroups:input_type -> example.proto.example.ListUserUserGroupsRequest
	10, // 55: example.proto.example.UserService.Get:input_type -> example.proto.example.GetUserRequest
	14, // 56: example.proto.example.UserService.List:input_type -> example.proto.example.ListUserRequest
	18, // 57: example.proto.example.UserService.Create:input_type -> example.proto.example.CreateUserRequest
	22, // 58: example.proto.example.UserService.Update:input_type -> example.proto.example.UpdateUserRequest
	26, // 59: example.proto.example.UserService.Delete:input_type -> example.proto.example.DeleteUserRequest
	15, // 60: example.proto.example.GroupService.ListGroupUsers:output_type -> example.proto.example.ListUserResponse
	9,  // 61: example.proto.example.GroupService.Get:output_type -> example.proto.example.GetGroupResponse
	13, // 62: example.proto.example.GroupService.List:output_type -> example.proto.example.ListGroupResponse
	17, // 63: example.proto.example.GroupService.Create:output_type -> example.proto.example.CreateGroupResponse
	21, // 64: example.proto.example.GroupService.Update:output_type -> example.proto.example.UpdateGroupResponse
	25, // 65: example.proto.example.GroupService.Delete:output_type -> example.proto.example.DeleteGroupResponse
	29, // 66: example.proto.example.UserService.SetStatus:output_type -> example.proto.example.SetUserStatusResponse
	13, // 67: example.proto.example.UserService.ListUserGroups:output_type -> example.proto.example.ListGroupResponse
	11, // 68: example.proto.example.UserService.Get:output_type -> example.proto.example.GetUserResponse
	15, // 69: example.proto.example.UserService.List:output_type -> example.proto.example.ListUserResponse
	19, // 70: example.proto.example.UserService.Create:output_type -> example.proto.example.CreateUserResponse
	23, // 71: example.proto.example.UserService.Update:output_type -> example.proto.example.UpdateUserResponse
	27, // 72: example.proto.example.UserService.Delete:output_type -> example.proto.example.DeleteUserResponse
	60, // [60:73] is the sub-list for method output_type
	47, // [47:60] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_proto_example_ent_service_proto_init() }
func file_proto_example_ent_service_proto_init() {
	if File_proto_example_ent_service_proto != nil {
		return
	}
	file_proto_example_ent_proto_init()
	file_proto_example_ent_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_example_ent_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_example_ent_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_example_ent_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_example_ent_service_proto_rawDesc), len(file_proto_example_ent_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_example_ent_service_proto_goTypes,
		DependencyIndexes: file_proto_example_ent_service_proto_depIdxs,
		EnumInfos:         file_proto_example_ent_service_proto_enumTypes,
		MessageInfos:      file_proto_example_ent_service_proto_msgTypes,
	}.Build()
	File_proto_example_ent_service_proto = out.File
	file_proto_example_ent_service_proto_goTypes = nil
	file_proto_example_ent_service_proto_depIdxs = nil
}
