// Code generated by "stringer -type APIMethod"; DO NOT EDIT.

package entproto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APIGet-1]
	_ = x[APIList-2]
	_ = x[APICreate-4]
	_ = x[APIUpdate-8]
	_ = x[APIDelete-16]
}

const (
	_APIMethod_name_0 = "APIGetAPIList"
	_APIMethod_name_1 = "APICreate"
	_APIMethod_name_2 = "APIUpdate"
	_APIMethod_name_3 = "APIDelete"
)

var (
	_APIMethod_index_0 = [...]uint8{0, 6, 13}
)

func (i APIMethod) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _APIMethod_name_0[_APIMethod_index_0[i]:_APIMethod_index_0[i+1]]
	case i == 4:
		return _APIMethod_name_1
	case i == 8:
		return _APIMethod_name_2
	case i == 16:
		return _APIMethod_name_3
	default:
		return "APIMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
