// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/syralon/entc-gen-go/example/internal/conf"
	"github.com/syralon/entc-gen-go/example/internal/data"
	"github.com/syralon/entc-gen-go/example/internal/server"
	"github.com/syralon/entc-gen-go/example/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data) (*kratos.App, func(), error) {
	client, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	services := service.NewServices(client)
	httpServer := server.NewHTTPServer(confServer, services)
	grpcServer := server.NewGRPCServer(confServer, services)
	app := newApp(httpServer, grpcServer)
	return app, func() {
	}, nil
}
